(() => {
  'use strict';
  const DATA=window.KKK_DATA;
  const LOCK_DAYS=8, LOCK_MS=LOCK_DAYS*24*60*60*1000;
  const STORAGE_KEY='kavitaKitchenUltimate_v1';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const uid=()=>crypto?.randomUUID?.()||('id_'+Date.now()+'_'+Math.random().toString(36).slice(2));
  const isoDate=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
  const normalize=s=>String(s||'').trim().toLowerCase();
  const emojiFor=d=>({Breakfast:'🥣',Lunch:'🍛',Dinner:'🍲',Desserts:'🍨',Shakes:'🥤',Coffee:'☕',Snacks:'🥟'}[d.category]||'🍽️');

  function defaultState(){return {
    meta:{updatedAt:new Date(0).toISOString(),version:1},
    party:{adults:2,kids:0,guestMode:false,guestAdults:0,guestKids:0},
    pantry:[],leftovers:[],exclusions:[],favorites:[],hidden:[],history:[],custom:[],ratings:{},votes:{},preference:{},planner:{},groceryChecked:{},
    weather:{kind:'pleasant',temperature:null,source:'default'},
    settings:{manualWeather:false},
    lastSearch:{category:'Dinner',results:[]}
  }}
  function mergeState(raw){const d=defaultState();if(!raw||typeof raw!=='object')return d;return {...d,...raw,meta:{...d.meta,...raw.meta},party:{...d.party,...raw.party},weather:{...d.weather,...raw.weather},settings:{...d.settings,...raw.settings},ratings:raw.ratings||{},votes:raw.votes||{},preference:raw.preference||{},planner:raw.planner||{},groceryChecked:raw.groceryChecked||{}}}
  function loadLocal(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY));if(raw)return mergeState(raw)}catch(e){}
    // Gentle migration from older Kavita ka Kitchen local state if present.
    for(const key of ['kavitaKaKitchen_v1','aajKyaBanaye_v1']){try{const old=JSON.parse(localStorage.getItem(key));if(old){const n=defaultState();n.history=old.history||[];n.custom=old.custom||[];n.favorites=old.favorites||[];return mergeState(n)}}catch(e){}}
    return defaultState();
  }
  let state=loadLocal();
  let supabaseClient=null,currentUser=null,syncTimer=null,syncInFlight=false,cloudReady=false;
  let selectedCategory=state.lastSearch?.category||'Dinner',selectedCuisine='Any',selectedTime='any',selectedEffort='any';
  let modes={guest:false,kids:false,jain:false,seasonal:false,pantry:false,leftover:false};
  let results=[],seenThisSearch=new Set(),currentRecipeDish=null,currentPlanDish=null,currentVoteDish=null,currentRatingDish=null;
  let inventoryMode='pantry',weekOffset=0,pendingSearch=false,deferredInstallPrompt=null;

  function saveLocal(sync=true){state.meta.updatedAt=new Date().toISOString();try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){};if(sync)scheduleSync();renderSyncPill()}
  function setSyncStatus(kind,text){const p=$('#syncPill');p.classList.remove('synced','syncing','error');if(kind)p.classList.add(kind);$('#syncText').textContent=text}
  function renderSyncPill(){if(!currentUser)return setSyncStatus('',navigator.onLine?'Local':'Offline');if(syncInFlight)return setSyncStatus('syncing','Syncing');if(cloudReady)return setSyncStatus('synced','Synced');setSyncStatus('',navigator.onLine?'Cloud ready':'Offline')}
  function scheduleSync(){if(!currentUser||!supabaseClient)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncToCloud(),900)}
  async function syncToCloud(force=false){if(!currentUser||!supabaseClient||syncInFlight||!navigator.onLine)return;syncInFlight=true;renderSyncPill();try{
      const payload={user_id:currentUser.id,state,updated_at:new Date().toISOString()};
      const {error}=await supabaseClient.from('kitchen_state').upsert(payload,{onConflict:'user_id'});
      if(error)throw error;cloudReady=true;setSyncStatus('synced','Synced');
    }catch(e){console.warn('Cloud sync:',e);setSyncStatus('error','Sync setup needed');if(force)toast('Cloud sync needs the Supabase table from supabase_schema.sql. Local data is safe.')}
    finally{syncInFlight=false}
  }
  async function loadCloud(){if(!currentUser||!supabaseClient)return;setSyncStatus('syncing','Loading');try{
      const {data,error}=await supabaseClient.from('kitchen_state').select('state,updated_at').eq('user_id',currentUser.id).maybeSingle();
      if(error)throw error;
      if(data?.state){const cloud=mergeState(data.state);const cloudTime=new Date(data.updated_at||cloud.meta.updatedAt||0).getTime();const localTime=new Date(state.meta.updatedAt||0).getTime();if(cloudTime>=localTime){state=cloud;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}else await syncToCloud();}
      else await syncToCloud();
      cloudReady=true;renderAll();setSyncStatus('synced','Synced');
    }catch(e){console.warn('Cloud load:',e);cloudReady=false;setSyncStatus('error','Local mode');renderAll()}
  }

  function allDishes(){return [...DATA.dishes,...state.custom.map((d,i)=>({category:'Dinner',name:'Family Dish '+(i+1),cuisine:'Other',majorIngredients:['mixed vegetables'],method:'curry',time:30,effort:'medium',quick:false,light:false,kids:true,guest:false,jain:true,seasonal:false,season:'all',nutrition:['balanced'],custom:true,...d,majorIngredients:Array.isArray(d.majorIngredients)?d.majorIngredients:(Array.isArray(d.ingredients)?d.ingredients:['mixed vegetables'])}))]}
  function byId(id){return allDishes().find(d=>d.id===id)}
  function isLocked(d){const now=Date.now();const n=normalize(d.name);return state.history.some(h=>now-new Date(h.date).getTime()<LOCK_MS && (h.dishId===d.id || normalize(h.name)===n))}
  function lockedUntil(d){const rows=state.history.filter(h=>h.dishId===d.id||normalize(h.name)===normalize(d.name)).sort((a,b)=>new Date(b.date)-new Date(a.date));if(!rows.length)return null;return new Date(new Date(rows[0].date).getTime()+LOCK_MS)}
  function isHidden(d){return state.hidden.includes(d.id)}
  function ratingFor(id){const r=state.ratings[id];return r?.count?r.sum/r.count:0}
  function voteScore(id){const v=state.votes[id]||{};return Object.values(v).reduce((a,n)=>a+Number(n||0),0)}
  function preferenceScore(d){const p=state.preference[d.id]||{};let score=50;score+=(state.favorites.includes(d.id)?18:0);const r=ratingFor(d.id);if(r)score+=(r-3)*7;score+=Math.min((p.cooked||0)*2,12);score+=voteScore(d.id)*3;score-=Math.min((p.skipped||0)*2,10);if(d.custom)score+=4;return Math.max(1,Math.min(99,Math.round(score)))}
  function hardEligible(d){if(d.category!==selectedCategory||isLocked(d)||isHidden(d))return false;if(modes.jain&&!d.jain)return false;const hay=normalize(d.name+' '+d.majorIngredients.join(' '));for(const ex of state.exclusions){if(ex&&hay.includes(normalize(ex)))return false}return true}
  function weatherMatch(d){const k=state.weather.kind;if(k==='hot')return d.light||['Shakes','Desserts'].includes(d.category)||d.majorIngredients.some(x=>/curd|coconut|mango|cucumber|lemon/i.test(x));if(k==='rainy')return ['Snacks','Coffee'].includes(d.category)||/khichdi|soup|kadhi|pakora/i.test(d.name);if(k==='cool')return d.guest||['Coffee','Desserts'].includes(d.category)||d.time>=30;return d.light||d.time<=35}
  function seasonMatch(d){const s=DATA.currentSeason();const veg=[...(DATA.seasonalVegetables[s]||[]),...(DATA.seasonalVegetables.all||[])];return d.season===s||d.majorIngredients.some(i=>veg.some(v=>normalize(i).includes(normalize(v))||normalize(v).includes(normalize(i))))}
  function overlap(items,ingredients){if(!items.length)return 0;const low=ingredients.map(normalize);return items.reduce((n,x)=>n+(low.some(i=>i.includes(normalize(x))||normalize(x).includes(i))?1:0),0)}
  function optionalExact(d){if(selectedCuisine!=='Any'&&d.cuisine!==selectedCuisine)return false;if(selectedTime!=='any'&&d.time>Number(selectedTime))return false;if(selectedEffort!=='any'&&d.effort!==selectedEffort)return false;if(modes.kids&&!d.kids)return false;if(modes.guest&&!d.guest)return false;if(modes.seasonal&&!seasonMatch(d))return false;if(modes.pantry&&state.pantry.length&&!overlap(state.pantry,d.majorIngredients))return false;if(modes.leftover&&state.leftovers.length&&!overlap(state.leftovers,d.majorIngredients))return false;return true}
  function rankDish(d){let s=preferenceScore(d);if(selectedCuisine==='Any'||d.cuisine===selectedCuisine)s+=18;else s-=4;if(selectedTime==='any'||d.time<=Number(selectedTime))s+=10;else s-=Math.min(10,(d.time-Number(selectedTime))/3);if(selectedEffort==='any'||d.effort===selectedEffort)s+=8;else s-=3;if(modes.kids)s+=d.kids?15:-10;else if(state.party.kids>0&&d.kids)s+=6;if(modes.guest||state.party.guestMode)s+=d.guest?16:-3;if(modes.seasonal)s+=seasonMatch(d)?15:-4;else if(seasonMatch(d))s+=3;if(modes.pantry)s+=overlap(state.pantry,d.majorIngredients)*10;if(modes.leftover)s+=overlap(state.leftovers,d.majorIngredients)*15;if(weatherMatch(d))s+=7;if(d.quick)s+=selectedTime==='15'||selectedTime==='30'?5:0;return s}
  function generate70(reset=true){if(reset)seenThisSearch=new Set();const candidates=allDishes().filter(hardEligible).filter(d=>!seenThisSearch.has(normalize(d.name))).map(d=>({d,exact:optionalExact(d),rank:rankDish(d)})).sort((a,b)=>(Number(b.exact)-Number(a.exact))||(b.rank-a.rank)||a.d.name.localeCompare(b.d.name));results=candidates.slice(0,70).map(x=>({...x.d,_exact:x.exact,_score:preferenceScore(x.d)}));results.forEach(d=>seenThisSearch.add(normalize(d.name)));state.lastSearch={category:selectedCategory,results:results.map(d=>d.id)};saveLocal(false);renderResults(candidates.filter(x=>x.exact).length);return results}

  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
  function openDialog(id){const el=$(id);if(el&&!el.open)el.showModal()}
  function closeDialog(id){const el=$(id);if(el?.open)el.close()}

  function setTab(tab){$$('.tab-page').forEach(x=>x.classList.toggle('active',x.id===`tab-${tab}`));$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));window.scrollTo({top:0,behavior:'smooth'});if(tab==='planner')renderPlanner();if(tab==='grocery')renderGrocery();if(tab==='insights')renderInsights()}
  function renderCategories(){const box=$('#categoryChips');box.innerHTML=DATA.CATEGORIES.map(c=>`<button class="category-chip ${c===selectedCategory?'active':''}" data-category="${esc(c)}">${emojiFor({category:c})} ${esc(c)}</button>`).join('');$$('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;renderCategories();renderModeSummary()})}
  function renderCuisine(){const opts=DATA.CUISINES.map(c=>`<option ${c===selectedCuisine?'selected':''}>${esc(c)}</option>`).join('');$('#cuisineSelect').innerHTML=opts;$('#customCuisine').innerHTML=DATA.CUISINES.filter(x=>x!=='Any').map(c=>`<option>${esc(c)}</option>`).join('');$('#customCategory').innerHTML=DATA.CATEGORIES.map(c=>`<option>${esc(c)}</option>`).join('')}
  function renderExclusions(){const box=$('#exclusionChips');box.innerHTML=state.exclusions.map((x,i)=>`<span class="tiny-chip">${esc(x)} <button data-remove-exclusion="${i}">×</button></span>`).join('');$$('[data-remove-exclusion]').forEach(b=>b.onclick=()=>{state.exclusions.splice(Number(b.dataset.removeExclusion),1);saveLocal();renderExclusions()})}
  function renderModeSummary(){const active=Object.entries(modes).filter(x=>x[1]).map(([k])=>({guest:'Guest',kids:'Kids',jain:'Jain',seasonal:'Seasonal',pantry:'At Home',leftover:'Leftovers'}[k]));$('#modeSummary').textContent=active.length?`Active: ${active.join(' • ')}`:'No special modes selected.'}
  function renderParty(){const p=state.party;$('#adultCount').textContent=p.adults;$('#kidCount').textContent=p.kids;$('#guestAdultCount').textContent=p.guestAdults||0;$('#guestKidCount').textContent=p.guestKids||0;$('#guestModeInParty').checked=!!p.guestMode;$('#guestCounts').classList.toggle('hidden',!p.guestMode);const totalA=p.adults+(p.guestAdults||0), totalK=p.kids+(p.guestKids||0);$('#partySummary').textContent=`${totalA} adult${totalA===1?'':'s'} + ${totalK} kid${totalK===1?'':'s'}`}
  function dishTags(d){const tags=[];tags.push(`${d.time} min`);tags.push(d.effort==='special'?'Special effort':d.effort==='easy'?'Easy':'Normal');if(d.jain)tags.push('Jain friendly');if(d.kids)tags.push('Kids');if(d.guest)tags.push('Guest');if(d.light)tags.push('Light');if(d.seasonal||seasonMatch(d))tags.push('Seasonal');return tags.slice(0,5)}
  function renderResults(exactCount=0){const total=results.length;const expanded=results.filter(x=>!x._exact).length;$('#resultsTitle').textContent=total?`${total} unique ${selectedCategory.toLowerCase()} ideas`:'No safe matches found';$('#resultsMeta').textContent=total?`${Math.min(exactCount,total)} exact matches first${expanded?` • ${expanded} intelligently broadened`:''} • ${state.party.adults+(state.party.guestAdults||0)} adults + ${state.party.kids+(state.party.guestKids||0)} kids`:'Try removing an exclusion or changing category. Jain and explicit exclusions are never relaxed.';$('#next70').classList.toggle('hidden',total===0);const box=$('#resultGrid');if(!total){box.innerHTML='<div class="empty-state"><span>🌿</span><h3>No safe ideas available</h3><p>Explicit exclusions and Jain rules are protected. Broaden another setting.</p></div>';return}
    box.innerHTML=results.map(d=>`<article class="dish-card" data-dish="${esc(d.id)}"><div class="dish-top"><span class="dish-emoji">${emojiFor(d)}</span><span class="score-badge">♥ ${d._score}/99 taste score</span></div><div class="dish-body"><div class="dish-meta">${esc(d.cuisine)} • ${esc(d.category)} ${d._exact?'':'• SMART EXPANDED'}</div><h3>${esc(d.name)}</h3><div class="dish-tags">${dishTags(d).map(t=>`<span class="dish-tag ${t==='Seasonal'?'smart':''}">${esc(t)}</span>`).join('')}</div><div class="dish-actions"><button data-action="recipe">Recipe</button><button data-action="vote">Vote</button><button data-action="plan">Plan</button><button data-action="fav" class="fav ${state.favorites.includes(d.id)?'active':''}">${state.favorites.includes(d.id)?'♥':'♡'}</button><button data-action="hide">Hide</button><button data-action="cook" class="cook">Cook</button></div></div></article>`).join('');
    $$('.dish-card').forEach(card=>card.onclick=e=>{const btn=e.target.closest('button[data-action]');if(!btn)return;const d=byId(card.dataset.dish);if(!d)return;handleDishAction(btn.dataset.action,d)})
  }
  function handleDishAction(action,d){if(action==='recipe')openRecipe(d);else if(action==='vote')openVotes(d);else if(action==='plan')openPlan(d);else if(action==='fav')toggleFav(d);else if(action==='hide')hideDish(d);else if(action==='cook')cookDish(d)}
  function toggleFav(d){const i=state.favorites.indexOf(d.id);if(i>=0)state.favorites.splice(i,1);else state.favorites.push(d.id);saveLocal();renderResults();renderInsights()}
  function hideDish(d){if(!confirm(`Never show “${d.name}” in normal recommendations? You can restore it from Kitchen Insights.`))return;state.hidden.push(d.id);state.preference[d.id]={...(state.preference[d.id]||{}),skipped:(state.preference[d.id]?.skipped||0)+2};saveLocal();results=results.filter(x=>x.id!==d.id);renderResults();toast('Dish hidden. You can restore it from Kitchen Insights.')}
  function cookDish(d){const p=state.party;state.history.unshift({id:uid(),dishId:d.id,name:d.name,category:d.category,cuisine:d.cuisine,date:new Date().toISOString(),adults:p.adults+(p.guestAdults||0),kids:p.kids+(p.guestKids||0)});const pref=state.preference[d.id]||{};state.preference[d.id]={...pref,cooked:(pref.cooked||0)+1,lastCooked:new Date().toISOString()};saveLocal();currentRatingDish=d;$('#ratingTitle').textContent=`How was ${d.name}?`;openDialog('#ratingDialog');results=results.filter(x=>x.id!==d.id);renderResults();renderToday();renderInsights();toast(`Saved. ${d.name} is resting for ${LOCK_DAYS} days.`)}
  function openRecipe(d){currentRecipeDish=d;$('#recipeTitle').textContent=d.name;$('#recipeSubtitle').textContent=`${d.cuisine} • ${d.time} min • ${d.effort} effort`;$('#recipeAdults').textContent=state.party.adults+(state.party.guestAdults||0);$('#recipeKids').textContent=state.party.kids+(state.party.guestKids||0);$('#recipeEmoji').textContent=emojiFor(d);renderRecipeBody();openDialog('#recipeDialog')}
  function renderRecipeBody(){if(!currentRecipeDish)return;const a=Number($('#recipeAdults').textContent),k=Number($('#recipeKids').textContent);const r=DATA.recipeFor(currentRecipeDish,a,k),n=DATA.nutritionIndicator(currentRecipeDish);$('#recipeBadges').innerHTML=dishTags(currentRecipeDish).map(t=>`<span class="dish-tag">${esc(t)}</span>`).join('');$('#recipeIngredients').innerHTML=r.ingredients.map(i=>`<div class="ingredient-row"><span>${esc(i.name)}</span><b>${esc(i.qty)} ${esc(i.unit)}</b></div>`).join('');$('#recipeSteps').innerHTML=r.steps.map(s=>`<li>${esc(s)}</li>`).join('');$('#nutritionPanel').innerHTML=[['Protein',n.protein],['Vegetables',n.vegetables],['Lightness',n.light],['Balance',n.balance]].map(([l,v])=>`<div class="nutrition-chip">${l}<b>${'●'.repeat(v)}${'○'.repeat(3-v)}</b></div>`).join('')}
  function openPlan(d){currentPlanDish=d;$('#planDishName').textContent=d.name;const start=getWeekStart();$('#planDay').innerHTML=[0,1,2,3,4,5,6].map(i=>{const day=new Date(start);day.setDate(start.getDate()+i);return `<option value="${isoDate(day)}">${day.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'})}</option>`}).join('');const meal=d.category==='Breakfast'?'Breakfast':d.category==='Lunch'?'Lunch':d.category==='Dinner'?'Dinner':'Dinner';$('#planMeal').value=meal;openDialog('#planDialog')}
  function savePlanEntry(){if(!currentPlanDish)return;const date=$('#planDay').value,meal=$('#planMeal').value;state.planner[date]=state.planner[date]||{};state.planner[date][meal]={dishId:currentPlanDish.id,name:currentPlanDish.name,category:currentPlanDish.category,adults:state.party.adults+(state.party.guestAdults||0),kids:state.party.kids+(state.party.guestKids||0)};saveLocal();closeDialog('#planDialog');renderPlanner();renderToday();toast('Added to weekly plan.')}
  function openVotes(d){currentVoteDish=d;$('#voteTitle').textContent=d.name;const p=state.party,totalA=Math.max(1,p.adults+(p.guestAdults||0)),totalK=p.kids+(p.guestKids||0),saved=state.votes[d.id]||{};let html='';for(let i=1;i<=totalA;i++){const key=`adult_${i}`,val=saved[key]||0;html+=voteRow(key,`Adult ${i}`,val)}for(let i=1;i<=totalK;i++){const key=`kid_${i}`,val=saved[key]||0;html+=voteRow(key,`Kid ${i}`,val)}$('#votePeople').innerHTML=html;$$('.vote-row button').forEach(b=>b.onclick=()=>{const row=b.closest('.vote-row');row.dataset.value=b.dataset.value;row.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});openDialog('#voteDialog')}
  function voteRow(key,label,val){return `<div class="vote-row" data-key="${key}" data-value="${val}"><b>${label}</b><button data-value="1" class="${val===1?'active':''}">👍</button><button data-value="-1" class="${val===-1?'active':''}">👎</button></div>`}
  function saveVotes(){if(!currentVoteDish)return;const map={};$$('#votePeople .vote-row').forEach(r=>map[r.dataset.key]=Number(r.dataset.value||0));state.votes[currentVoteDish.id]=map;saveLocal();closeDialog('#voteDialog');renderResults();toast('Family votes saved. Preference score updated.')}
  function saveRating(v){if(!currentRatingDish)return;const r=state.ratings[currentRatingDish.id]||{sum:0,count:0};r.sum+=Number(v);r.count+=1;r.last=Number(v);state.ratings[currentRatingDish.id]=r;saveLocal();closeDialog('#ratingDialog');renderInsights();toast('Rating saved. Future suggestions will learn from it.')}

  function openPartyForSearch(){renderParty();pendingSearch=true;openDialog('#partyDialog')}
  function confirmParty(){const p=state.party;p.guestMode=$('#guestModeInParty').checked;modes.guest=p.guestMode||modes.guest;saveLocal();renderParty();closeDialog('#partyDialog');if(pendingSearch){pendingSearch=false;generate70(true);setTab('discover')}}
  function changeCounter(key,delta){state.party[key]=Math.max(key==='adults'?1:0,Number(state.party[key]||0)+delta);renderParty()}

  function openInventory(mode){inventoryMode=mode;const isPantry=mode==='pantry';$('#inventoryKicker').textContent=isPantry?'Available at Home':'Leftover Mode';$('#inventoryTitle').textContent=isPantry?'What’s available at home?':'What leftovers should we use?';$('#inventoryCopy').textContent=isPantry?'Add ingredients you already have. We’ll rank ideas that use them.':'Add leftover ingredients or cooked components. We’ll prioritize ways to reuse them.';$('#inventoryInput').value='';renderInventoryChips();openDialog('#inventoryDialog')}
  function renderInventoryChips(){const arr=state[inventoryMode]||[];$('#inventoryChips').innerHTML=arr.length?arr.map((x,i)=>`<span class="tiny-chip">${esc(x)} <button data-remove-inventory="${i}">×</button></span>`).join(''):'<span class="tiny-chip">Nothing added yet</span>';$$('[data-remove-inventory]').forEach(b=>b.onclick=()=>{state[inventoryMode].splice(Number(b.dataset.removeInventory),1);saveLocal();renderInventoryChips()})}
  function addInventory(){const val=$('#inventoryInput').value.trim();if(!val)return;const arr=state[inventoryMode];val.split(',').map(x=>x.trim()).filter(Boolean).forEach(x=>{if(!arr.some(y=>normalize(y)===normalize(x)))arr.push(x)});$('#inventoryInput').value='';saveLocal();renderInventoryChips()}
  function saveExclusions(){const val=$('#excludeInput').value.trim();if(val){val.split(',').map(x=>x.trim()).filter(Boolean).forEach(x=>{if(!state.exclusions.some(y=>normalize(y)===normalize(x)))state.exclusions.push(x)});$('#excludeInput').value='';saveLocal();renderExclusions()}}

  function getWeekStart(){const d=new Date();const day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day+weekOffset*7);return d}
  function renderPlanner(){const start=getWeekStart(),end=new Date(start);end.setDate(start.getDate()+6);$('#weekLabel').textContent=`${start.toLocaleDateString(undefined,{day:'numeric',month:'short'})} – ${end.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}`;const today=isoDate();let html='';for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=isoDate(d),row=state.planner[key]||{};html+=`<div class="day-column ${key===today?'today':''}"><div class="day-head"><b>${d.toLocaleDateString(undefined,{weekday:'short'})}</b><span>${d.toLocaleDateString(undefined,{day:'numeric',month:'short'})}</span></div>${['Breakfast','Lunch','Dinner'].map(meal=>plannerSlot(key,meal,row[meal])).join('')}</div>`}$('#weekGrid').innerHTML=html;$$('.meal-slot[data-date]').forEach(slot=>slot.onclick=e=>{const remove=e.target.closest('[data-remove-plan]');if(remove){const {date,meal}=remove.dataset;delete state.planner[date]?.[meal];saveLocal();renderPlanner();renderToday();return}if(slot.classList.contains('empty')){selectedCategory=slot.dataset.meal;renderCategories();setTab('discover');toast(`Search ${slot.dataset.meal.toLowerCase()} ideas, then tap Plan.`)}})}
  function plannerSlot(date,meal,entry){if(!entry)return `<div class="meal-slot empty" data-date="${date}" data-meal="${meal}"><div><label>${meal}</label><br>＋ Add meal</div></div>`;return `<div class="meal-slot" data-date="${date}" data-meal="${meal}"><label>${meal}</label><b>${esc(entry.name)}</b><small>${entry.adults}A + ${entry.kids}K</small><button class="mini-link" data-remove-plan="1" data-date="${date}" data-meal="${meal}">×</button></div>`}
  function autoPlanWeek(){const start=getWeekStart(),used=new Set();for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=isoDate(d);state.planner[key]=state.planner[key]||{};for(const meal of ['Breakfast','Lunch','Dinner']){if(state.planner[key][meal]){used.add(normalize(state.planner[key][meal].name));continue}const candidates=allDishes().filter(x=>x.category===meal&&!isHidden(x)&&!isLocked(x)&&!used.has(normalize(x.name))).sort((a,b)=>preferenceScore(b)-preferenceScore(a));const pick=candidates[0];if(pick){used.add(normalize(pick.name));state.planner[key][meal]={dishId:pick.id,name:pick.name,category:meal,adults:state.party.adults,kids:state.party.kids}}}}saveLocal();renderPlanner();renderToday();toast('Week auto-planned with unique dishes.')}
  function renderToday(){const row=state.planner[isoDate()]||{};$('#todayPlan').innerHTML=['Breakfast','Lunch','Dinner'].map(meal=>{const e=row[meal];return `<button class="plan-today-card" data-today-meal="${meal}"><span>${meal}</span><b>${esc(e?.name||'Not planned')}</b><small>${e?`${e.adults} adults + ${e.kids} kids`:'Tap to discover ideas'}</small></button>`}).join('');$$('[data-today-meal]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.todayMeal;renderCategories();setTab('discover')});renderParty()}

  function categoryGroup(name){const n=normalize(name);if(/milk|curd|paneer|cream|cheese|butter/.test(n))return 'Dairy & Chilled';if(/rice|flour|dal|lentil|oats|semolina|poha|bread|pav|vermicelli|millet/.test(n))return 'Grains & Pulses';if(/spice|salt|oil|ghee|sugar|jaggery|syrup|coffee/.test(n))return 'Pantry';if(/tomato|capsicum|spinach|peas|carrot|bean|okra|brinjal|gourd|corn|mango|banana|apple|berry|lemon|coconut|coriander|fenugreek|pumpkin|cucumber/.test(n))return 'Produce';return 'Other'}
  function buildGrocery(){const start=getWeekStart(),items=[];for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const row=state.planner[isoDate(d)]||{};Object.values(row).forEach(e=>{const dish=byId(e.dishId);if(!dish)return;const r=DATA.recipeFor(dish,e.adults||2,e.kids||0);r.ingredients.forEach(x=>items.push(x))})}const map=new Map();for(const x of items){if(typeof x.qty!=='number')continue;const key=`${normalize(x.name)}|${x.unit}`;const old=map.get(key)||{name:x.name,qty:0,unit:x.unit};old.qty+=Number(x.qty);map.set(key,old)}return [...map.values()].sort((a,b)=>categoryGroup(a.name).localeCompare(categoryGroup(b.name))||a.name.localeCompare(b.name))}
  function renderGrocery(){const items=buildGrocery(),pantryLow=state.pantry.map(normalize);$('#grocerySummary').innerHTML=items.length?`<b>${items.length} combined ingredients</b><p style="font-size:10px;color:var(--muted);margin:5px 0 0">Generated from the visible week. Items already listed in “What’s Available at Home?” are marked as stocked.</p>`:'<b>No planned meals yet</b><p style="font-size:10px;color:var(--muted)">Add meals to the weekly planner first.</p>';const groups={};items.forEach(x=>(groups[categoryGroup(x.name)]??=[]).push(x));$('#groceryGrid').innerHTML=Object.entries(groups).map(([g,rows])=>`<div class="grocery-card"><h3>${esc(g)}</h3>${rows.map(x=>{const key=normalize(x.name),stocked=pantryLow.some(p=>key.includes(p)||p.includes(key));const checked=!!state.groceryChecked[key];return `<label class="grocery-item"><input type="checkbox" data-grocery="${esc(key)}" ${checked?'checked':''}><span>${esc(x.name)}${stocked?' · ✓ at home':''}</span><b>${Math.round(x.qty*10)/10} ${esc(x.unit)}</b></label>`}).join('')}</div>`).join('');$$('[data-grocery]').forEach(c=>c.onchange=()=>{state.groceryChecked[c.dataset.grocery]=c.checked;saveLocal()})}

  function renderInsights(){const hist=state.history,unique=new Set(hist.map(h=>normalize(h.name))).size;const variety=hist.length?Math.round(unique/hist.length*100):100;const favs=state.favorites.map(byId).filter(Boolean).sort((a,b)=>preferenceScore(b)-preferenceScore(a));const cuisines={};hist.forEach(h=>cuisines[h.cuisine]=(cuisines[h.cuisine]||0)+1);const cuisineRanks=Object.entries(cuisines).sort((a,b)=>b[1]-a[1]).slice(0,8);const leaders=allDishes().filter(d=>!isHidden(d)).sort((a,b)=>preferenceScore(b)-preferenceScore(a)).slice(0,8);$('#insightMetrics').innerHTML=[[hist.length,'Meals saved'],[favs.length,'Favourites'],[state.hidden.length,'Hidden dishes'],[`${variety}%`,'Variety score']].map(([v,l])=>`<div class="metric"><b>${v}</b><span>${l}</span></div>`).join('');$('#topFavourites').innerHTML=favs.length?favs.slice(0,8).map((d,i)=>rankRow(i+1,d.name,`${preferenceScore(d)}/99`)).join(''):'<p class="fineprint">No favourites yet.</p>';$('#topCuisines').innerHTML=cuisineRanks.length?cuisineRanks.map(([n,v],i)=>rankRow(i+1,n,`${v} cooked`)).join(''):'<p class="fineprint">Cooked meals will build this insight.</p>';$('#hiddenList').innerHTML=state.hidden.length?state.hidden.map(id=>byId(id)).filter(Boolean).slice(0,10).map((d,i)=>`<div class="rank-row"><b>${esc(d.name)}</b><button class="link-btn" data-unhide="${esc(d.id)}">Restore</button></div>`).join(''):'<p class="fineprint">Nothing is permanently hidden.</p>';$('#preferenceLeaders').innerHTML=leaders.map((d,i)=>rankRow(i+1,d.name,`${preferenceScore(d)}/99`)).join('');$$('[data-unhide]').forEach(b=>b.onclick=()=>{state.hidden=state.hidden.filter(x=>x!==b.dataset.unhide);saveLocal();renderInsights();toast('Dish restored.')})}
  function rankRow(i,n,v){return `<div class="rank-row"><b>${i}. ${esc(n)}</b><span>${esc(v)}</span></div>`}

  function renderWeather(){const w=state.weather;const label={hot:'Hot day',rainy:'Rainy mood',cool:'Cool weather',pleasant:'Pleasant weather'}[w.kind]||'Pleasant weather';$('#weatherTitle').textContent=w.temperature!=null?`${Math.round(w.temperature)}°C • ${label}`:label;$('#weatherCopy').textContent={hot:'Lighter meals, shakes, curd and cooling ingredients get a boost.',rainy:'Warm comfort food, snacks, coffee and khichdi get a boost.',cool:'Warm, richer and guest-style meals get a boost.',pleasant:'Balanced, fresh and quick ideas get a small boost.'}[w.kind]}
  async function loadWeather(){if(state.settings.manualWeather)return renderWeather();try{const r=await fetch('/api/weather');const x=await r.json();if(x.ok){state.weather={kind:x.kind,temperature:x.temperature,source:'Surat weather'};saveLocal(false)}}catch(e){}renderWeather()}
  function setManualWeather(k){state.weather={kind:k,temperature:null,source:'manual'};state.settings.manualWeather=true;saveLocal();renderWeather();closeDialog('#weatherDialog');toast('Weather preference updated.')}
  function renderSeason(){const s=DATA.currentSeason(),list=[...(DATA.seasonalVegetables[s]||[])].slice(0,5);$('#seasonTitle').textContent=`${s[0].toUpperCase()+s.slice(1)} picks`;$('#seasonCopy').textContent=`Great now: ${list.join(', ')}.`}

  function addCustomDish(){const name=$('#customName').value.trim();if(!name)return toast('Add a dish name.');if(/egg|anda|omelette|omelet/i.test(name+' '+$('#customIngredients').value))return toast('Kavita ka Kitchen is pure vegetarian — egg items are not allowed.');const category=$('#customCategory').value,ingredients=$('#customIngredients').value.split(',').map(x=>x.trim()).filter(Boolean);const root=/potato|aloo|carrot|beetroot|onion|garlic|sweet potato/i.test(ingredients.join(' '));const d={id:'custom_'+uid(),category,name,baseName:name,cuisine:$('#customCuisine').value,majorIngredients:ingredients.length?ingredients:['mixed vegetables'],method:['Shakes'].includes(category)?'blend':category==='Coffee'?'coffee':category==='Desserts'?'dessert':'curry',time:Number($('#customTime').value||30),effort:$('#customEffort').value,quick:Number($('#customTime').value||30)<=20,light:false,kids:true,guest:false,jain:!root,seasonal:false,season:'all',nutrition:['balanced'],custom:true};state.custom.push(d);saveLocal();closeDialog('#addDishDialog');toast('Family dish added to recommendations.');$('#customName').value='';$('#customIngredients').value=''}

  function renderAll(){renderCategories();renderCuisine();renderExclusions();renderModeSummary();renderParty();renderToday();renderPlanner();renderGrocery();renderInsights();renderWeather();renderSeason();$('#accountEmail').textContent=currentUser?.email||'Signed in';$('#profileInitial').textContent=(currentUser?.email?.[0]||'K').toUpperCase()}

  /* Authentication */
  let authMode='login';
  function authMessage(text,type=''){const el=$('#authMessage');el.textContent=text;el.className='message'+(type?' '+type:'');el.classList.remove('hidden')}
  function clearAuthMessage(){$('#authMessage').classList.add('hidden');$('#authMessage').textContent=''}
  function showAuthMode(mode){authMode=mode;clearAuthMessage();$('#emailWrap').classList.remove('hidden');$('#passwordWrap').classList.remove('hidden');$('#confirmWrap').classList.add('hidden');$('#forgotPassword').classList.remove('hidden');$('#backToLogin').classList.add('hidden');$('#authPassword').value='';$('#authConfirm').value='';if(mode==='login'){$('#authTitle').textContent='Welcome back';$('#authCopy').textContent='Sign in to open your family’s private kitchen planner and synced meal history.';$('#authSubmit').textContent='Sign in securely';$('#authPassword').autocomplete='current-password'}else if(mode==='forgot'){$('#authTitle').textContent='Reset password';$('#authCopy').textContent='Enter your email. Supabase will send a secure recovery link if email delivery is configured.';$('#passwordWrap').classList.add('hidden');$('#authSubmit').textContent='Send recovery email';$('#forgotPassword').classList.add('hidden');$('#backToLogin').classList.remove('hidden')}else{$('#authTitle').textContent='Create a new password';$('#authCopy').textContent='Choose a password for this kitchen account.';$('#emailWrap').classList.add('hidden');$('#confirmWrap').classList.remove('hidden');$('#authSubmit').textContent='Save password';$('#forgotPassword').classList.add('hidden');$('#backToLogin').classList.remove('hidden');$('#authPassword').autocomplete='new-password'}}
  function authError(e){const m=String(e?.message||e||'Login failed');if(/invalid login/i.test(m))return 'Email or password is incorrect.';return m}
  function revealApp(user){currentUser=user;document.body.classList.remove('auth-locked');$('#accountEmail').textContent=user?.email||'Signed in';renderAll();loadCloud();loadWeather()}
  function lockApp(){currentUser=null;document.body.classList.add('auth-locked');showAuthMode('login')}
  async function initSupabase(){try{const r=await fetch('/api/config',{cache:'no-store'});const c=await r.json();if(!c.configured)throw new Error(c.message||'Supabase not configured');supabaseClient=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'kavita-kitchen-auth-v2'}});supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){document.body.classList.add('auth-locked');showAuthMode('set-password');return}if(event==='SIGNED_OUT'){lockApp();return}if(session?.user&&event==='SIGNED_IN')revealApp(session.user)});const {data,error}=await supabaseClient.auth.getSession();if(error)throw error;if(data.session?.user)revealApp(data.session.user);else lockApp()}catch(e){document.body.classList.add('auth-locked');showAuthMode('login');authMessage(authError(e),'error')}}
  async function submitAuth(e){e.preventDefault();if(!supabaseClient)return authMessage('Secure login is not connected yet. Check Vercel environment variables.','error');const email=$('#authEmail').value.trim(),pass=$('#authPassword').value,confirm=$('#authConfirm').value;$('#authSubmit').disabled=true;try{if(authMode==='login'){const {data,error}=await supabaseClient.auth.signInWithPassword({email,password:pass});if(error)throw error;if(data.user)revealApp(data.user)}else if(authMode==='forgot'){const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.origin});if(error)throw error;authMessage('Recovery email requested. If SMTP is unavailable, an admin can set the password directly in Supabase.','ok')}else{if(pass.length<6)throw new Error('Use at least 6 characters.');if(pass!==confirm)throw new Error('Passwords do not match.');const {error}=await supabaseClient.auth.updateUser({password:pass});if(error)throw error;authMessage('Password saved. You can continue.','ok');setTimeout(()=>showAuthMode('login'),800)}}catch(err){authMessage(authError(err),'error')}finally{$('#authSubmit').disabled=false}}

  /* Install */
  function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
  function showInstall(){if(isStandalone())return toast('Kavita ka Kitchen is already installed.');if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>deferredInstallPrompt=null);return}$('#installGuide').innerHTML='<p><b>Android Chrome:</b> open the browser menu (⋮), choose <b>Install app</b> or <b>Add to Home screen</b>, then confirm.</p><p>The Vercel site must be served over HTTPS.</p>';openDialog('#installDialog')}

  /* Events */
  $$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
  $('#heroDiscover').onclick=()=>{setTab('discover');setTimeout(()=>openPartyForSearch(),100)};
  $('#editParty').onclick=()=>{pendingSearch=false;renderParty();openDialog('#partyDialog')};
  $$('[data-counter]').forEach(b=>b.onclick=()=>changeCounter(b.dataset.counter,Number(b.dataset.delta)));
  $('#guestModeInParty').onchange=e=>{$('#guestCounts').classList.toggle('hidden',!e.target.checked)};
  $('#confirmParty').onclick=confirmParty;
  $('#searchButton').onclick=openPartyForSearch;
  $('#next70').onclick=()=>generate70(false);
  $('#cuisineSelect').onchange=e=>selectedCuisine=e.target.value;
  $('#timeSelect').onchange=e=>selectedTime=e.target.value;
  $('#effortSelect').onchange=e=>selectedEffort=e.target.value;
  $$('.mode-chip').forEach(b=>b.onclick=()=>{const m=b.dataset.mode;modes[m]=!modes[m];b.classList.toggle('active',modes[m]);if(m==='pantry'&&modes[m])openInventory('pantry');if(m==='leftover'&&modes[m])openInventory('leftovers');renderModeSummary()});
  $('#saveExclusions').onclick=saveExclusions;$('#excludeInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();saveExclusions()}};
  $('#quickPantry').onclick=()=>{modes.pantry=true;$$('[data-mode="pantry"]').forEach(x=>x.classList.add('active'));renderModeSummary();openInventory('pantry')};
  $('#quickLeftovers').onclick=()=>{modes.leftover=true;$$('[data-mode="leftover"]').forEach(x=>x.classList.add('active'));renderModeSummary();openInventory('leftovers')};
  $('#inventoryAdd').onclick=addInventory;$('#inventoryInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addInventory()}};$('#inventoryDone').onclick=()=>{saveLocal();closeDialog('#inventoryDialog');setTab('discover')};
  $('#recipeAdultMinus').onclick=()=>{$('#recipeAdults').textContent=Math.max(1,Number($('#recipeAdults').textContent)-1);renderRecipeBody()};$('#recipeAdultPlus').onclick=()=>{$('#recipeAdults').textContent=Number($('#recipeAdults').textContent)+1;renderRecipeBody()};$('#recipeKidMinus').onclick=()=>{$('#recipeKids').textContent=Math.max(0,Number($('#recipeKids').textContent)-1);renderRecipeBody()};$('#recipeKidPlus').onclick=()=>{$('#recipeKids').textContent=Number($('#recipeKids').textContent)+1;renderRecipeBody()};
  $('#savePlan').onclick=savePlanEntry;$('#saveVotes').onclick=saveVotes;$$('#ratingStars [data-rating]').forEach(b=>b.onclick=()=>saveRating(b.dataset.rating));
  $('#addDish').onclick=()=>openDialog('#addDishDialog');$('#saveCustomDish').onclick=addCustomDish;
  $('#plannerPrev').onclick=()=>{weekOffset--;renderPlanner()};$('#plannerNext').onclick=()=>{weekOffset++;renderPlanner()};$('#autoPlanWeek').onclick=autoPlanWeek;
  $('#generateGrocery').onclick=renderGrocery;
  $('#weatherManual').onclick=()=>openDialog('#weatherDialog');$$('[data-weather]').forEach(b=>b.onclick=()=>setManualWeather(b.dataset.weather));
  $('#syncNow').onclick=()=>syncToCloud(true);$('#profileSync').onclick=()=>syncToCloud(true);
  $('#installButton').onclick=showInstall;$('#profileInstall').onclick=showInstall;
  $('#profileButton').onclick=()=>openDialog('#profileDialog');$('#signOut').onclick=async()=>{closeDialog('#profileDialog');if(supabaseClient)await supabaseClient.auth.signOut();lockApp()};
  $$('[data-close]').forEach(b=>b.onclick=()=>closeDialog('#'+b.dataset.close));
  $('#loginForm').onsubmit=submitAuth;$('#forgotPassword').onclick=()=>showAuthMode('forgot');$('#backToLogin').onclick=()=>showAuthMode('login');
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});window.addEventListener('online',()=>{renderSyncPill();scheduleSync()});window.addEventListener('offline',renderSyncPill);
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}));

  renderAll();initSupabase();
})();
