import test from 'node:test';
import assert from 'node:assert/strict';
import config,{browserSafeKey} from '../api/config.js';
import deletion from '../api/delete-account.js';
function response(){return {code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.body=v;return this;}};}
test('browser config refuses service-role JWTs and secret keys',()=>{const jwt=role=>'x.'+Buffer.from(JSON.stringify({role})).toString('base64url')+'.x';assert.equal(browserSafeKey('sb_secret_not-for-browser'),false);assert.equal(browserSafeKey(jwt('service_role')),false);assert.equal(browserSafeKey(jwt('anon')),true);assert.equal(browserSafeKey('sb_publishable_safe'),true);});
test('account deletion rejects methods, cross-origin requests and missing confirmation',async()=>{process.env.APP_ORIGIN='https://app.example';for(const [req,expected] of [[{method:'GET',headers:{}},405],[{method:'POST',headers:{origin:'https://evil.example'}},403],[{method:'POST',headers:{origin:'https://app.example','content-type':'application/json'},body:{}},400]]){const res=response();await deletion(req,res);assert.equal(res.code,expected);}});
test('account deletion uses verified identity, never a client-supplied account ID',async()=>{const original=globalThis.fetch,env={...process.env},calls=[];Object.assign(process.env,{APP_ORIGIN:'https://app.example',SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test',SUPABASE_SERVICE_ROLE_KEY:'server-secret'});globalThis.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({id:'verified-user',last_sign_in_at:new Date().toISOString()})};};try{const res=response();await deletion({method:'POST',headers:{origin:'https://app.example','content-type':'application/json',authorization:'Bearer valid-user-token'},body:{confirmation:'DELETE',user_id:'victim'}},res);assert.equal(res.code,200);assert.equal(res.body.deleted,true);assert.match(calls[1].url,/verified-user$/);assert.ok(!calls[1].url.includes('victim'));}finally{globalThis.fetch=original;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);}});
test('account deletion requires recent authentication',async()=>{const original=globalThis.fetch,env={...process.env};Object.assign(process.env,{APP_ORIGIN:'https://app.example',SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test',SUPABASE_SERVICE_ROLE_KEY:'server-secret'});let calls=0;globalThis.fetch=async()=>{calls++;return {ok:true,json:async()=>({id:'verified',last_sign_in_at:'2000-01-01T00:00:00Z'})};};try{const res=response();await deletion({method:'POST',headers:{origin:'https://app.example','content-type':'application/json',authorization:'Bearer valid'},body:{confirmation:'DELETE'}},res);assert.equal(res.code,401);assert.equal(calls,1);}finally{globalThis.fetch=original;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);}});
