import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {KitchenStore,supabaseRemote} from '../src/storage.js';
Object.defineProperty(globalThis.navigator,'onLine',{value:true,configurable:true});
function remote(uid){const rows=new Map();return {rows,async write(r){const old=rows.get(r.id);if(old?.mutation_id===r.mutation_id)return {record:old};if((old?.version||0)!==r.version)return {conflict:true};const record={...r,user_id:uid,dirty:undefined,version:r.version+1};rows.set(r.id,record);return {record};},async read(){return [...rows.values()];},async one(id){return rows.get(id);}};}
test('private offline caches cannot bleed from A to B or guest',async()=>{const a=await new KitchenStore('scope-a',null).open();await a.put('recipe','recipe:secret',{name:'Private A recipe'});a.close();const b=await new KitchenStore('scope-b',null).open();assert.equal(b.get('recipe').length,0);b.close();const again=await new KitchenStore('scope-a',null).open();assert.equal(again.get('recipe')[0].name,'Private A recipe');again.close();assert.throws(()=>new KitchenStore(null));});
test('offline queue survives reload and syncs once',async()=>{const uid='offline',cloud=remote(uid);let a=await new KitchenStore(uid,null).open();await a.put('pantry','pantry:1',{name:'rice'});a.close();a=await new KitchenStore(uid,cloud).open();assert.equal(a.rows.get('pantry:1').dirty,true);await a.sync();assert.equal(cloud.rows.size,1);assert.equal(a.rows.get('pantry:1').dirty,false);await a.sync();assert.equal(cloud.rows.get('pantry:1').version,1);a.close();});
test('concurrent changes to different records merge across devices',async()=>{const uid='merge',cloud=remote(uid),a=await new KitchenStore(uid,cloud).open(),b=await new KitchenStore(uid,cloud).open();await a.put('pantry','pantry:a',{name:'rice'});await b.put('pantry','pantry:b',{name:'dal'});await a.sync();await b.sync();await a.sync();assert.equal(a.get('pantry').length,2);assert.equal(b.get('pantry').length,2);a.close();b.close();});
test('same-record conflicts require explicit resolution',async()=>{const uid='conflict',cloud=remote(uid),a=await new KitchenStore(uid,cloud).open();await a.put('combo','combo:1',{name:'Original'});await a.sync();const b=await new KitchenStore(uid,cloud).open();await b.sync();await a.put('combo','combo:1',{name:'A changed'});await b.put('combo','combo:1',{name:'B changed'});await a.sync();await b.sync();assert.ok(b.conflicts.has('combo:1'));assert.equal(cloud.rows.get('combo:1').payload.name,'A changed');await b.resolve('combo:1',true);assert.equal(cloud.rows.get('combo:1').payload.name,'B changed');a.close();b.close();});
test('delete tombstones propagate without resurrecting records',async()=>{const uid='delete',cloud=remote(uid),a=await new KitchenStore(uid,cloud).open();await a.put('favorite','favorite:one',{dishId:'one'});await a.sync();await a.remove('favorite:one');await a.sync();assert.equal(a.get('favorite').length,0);assert.ok(cloud.rows.get('favorite:one').deleted_at);a.close();});
test('account switch prevents late writes or data hydration',async()=>{let resume;const uid='switch',cloud=remote(uid);cloud.read=()=>new Promise(r=>resume=r);const a=await new KitchenStore(uid,cloud).open();const task=a.sync();await Promise.resolve();a.close();resume([{id:'history:secret',kind:'history',user_id:uid,payload:{name:'A dinner'}}]);await task;assert.equal(a.rows.size,0);});
test('shared auth client cannot send user A payload using user B credentials',async()=>{const client={auth:{getSession:async()=>({data:{session:{user:{id:'B'},access_token:'B-token'}}})}};const r=supabaseRemote(client,'A',{url:'https://example.supabase.co',key:'public'});await assert.rejects(()=>r.write({id:'secret',kind:'recipe',payload:{name:'A'}}),/Account changed/);});
