import fs from 'node:fs/promises';
await fs.writeFile('index.html',`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#194b3d"><meta name="description" content="Never wonder what to cook again. Vegetarian, eggless meal planning for your home, workplace and celebrations. Private kitchens, good food, less waste."><meta name="application-name" content="Kavita ka Kitchen"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><title>Kavita ka Kitchen — Never Wonder What to Cook Again</title><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/art/brand.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/icons/apple-touch-icon.png"><link rel="preload" href="/fonts/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/styles.css"></head>
<body><a class="skip-link" href="#main">Skip to content</a><aside class="sidebar"><button class="brand" data-nav="today" aria-label="Kavita ka Kitchen home"><img class="brand-mark" src="/art/brand.svg" alt="" width="39" height="45"><span class="brand-name">Kavita ka<br>Kitchen<small>Good food. Good living.</small></span></button><p class="nav-label">YOUR EVERYDAY KITCHEN</p><nav id="nav" aria-label="Main navigation"></nav><div class="sidebar-bottom"><div class="sidebar-note"><span aria-hidden="true">❧</span><b>Made with a little love.</b>Pure vegetarian. Always eggless.<br>Every kitchen is welcome.</div><p class="sidebar-footer">A happier table starts here.</p></div></aside><div class="workspace"><header class="topbar"><button class="mobile-brand" data-nav="today"><img src="/art/brand.svg" alt="" width="28" height="32"><span>Kavita ka Kitchen</span></button><div class="topbar-left"><span class="breadcrumb">A place for your kitchen</span><button id="kitchenButton" class="kitchen-select" data-action="headcount">Home Kitchen</button></div><div class="topbar-actions"><button id="syncStatus" class="sync-status" data-action="sync" aria-live="polite">Your kitchen, kept private</button><button id="accountButton" class="primary small" data-nav="settings">Sign in</button></div></header><main id="main" tabindex="-1"><noscript><h1>Kavita ka Kitchen</h1><p>Enable JavaScript to discover meals and use your private kitchen planner.</p></noscript></main></div><nav class="mobile-nav" id="mobileNav" aria-label="Mobile navigation"></nav><dialog id="dialog" aria-labelledby="dialogTitle"><div id="dialogBody"></div></dialog><div id="toast" class="toast" role="status" aria-live="polite"></div><script type="module" src="/assets/app.js"></script></body></html>`);
await fs.writeFile('manifest.webmanifest',JSON.stringify({id:'/',name:'Kavita ka Kitchen — Your Smart Food Companion',short_name:'Kavita Kitchen',description:'Pure vegetarian, eggless meal planning for home, office, canteens and events.',lang:'en-IN',start_url:'/',scope:'/',display:'standalone',background_color:'#fafbf7',theme_color:'#194b3d',categories:['food','lifestyle','utilities'],icons:[{src:'/icons/icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},{src:'/icons/icon-512.png',sizes:'512x512',type:'image/png',purpose:'any'},{src:'/icons/icon-maskable-512.png',sizes:'512x512',type:'image/png',purpose:'maskable'}],shortcuts:[{name:'Discover meals',url:'/?tab=discover'},{name:'My week',url:'/?tab=planner'}]},null,2));
await fs.writeFile('service-worker.js',`const CACHE='kkk-public-v3.0.0';
const SHELL=['/index.html','/assets/styles.css','/art/brand.svg','/art/kitchen-bowl.svg','/manifest.webmanifest','/data/manifest.json','/data/aliases.json','/fonts/manrope.woff2','/fonts/fraunces.woff2','/icons/icon-192.png','/icons/icon-512.png',/* BUILD_ASSETS */];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('kkk-public-')&&k!==CACHE||k.startsWith('kavita-kitchen-')).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 const req=event.request,url=new URL(req.url);
 if(req.method!=='GET'||url.origin!==self.location.origin||url.pathname.startsWith('/api/'))return;
 if(req.mode==='navigate'){event.respondWith(fetch(req).then(async r=>{if(r.ok&&(r.headers.get('content-type')||'').includes('text/html')){const cache=await caches.open(CACHE);await cache.put('/index.html',r.clone());}return r;}).catch(()=>caches.match('/index.html')));return;}
 const allowed=/^\/(assets|art|icons|fonts|data)\//.test(url.pathname)||url.pathname==='/manifest.webmanifest';if(!allowed)return;
 event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(async r=>{if(r.ok){const cache=await caches.open(CACHE);await cache.put(req,r.clone());}return r;})));
});
// Private changes use the authenticated per-user IndexedDB queue, never Cache Storage.
// Foreground reconnect / visibility events flush it. No credentials are exposed to the worker.
`);
await fs.writeFile('vercel.json',JSON.stringify({buildCommand:'node scripts/build.mjs',outputDirectory:'dist',installCommand:'pnpm install --frozen-lockfile',functions:{'api/catalog.js':{includeFiles:'catalog/generated/dishes.json'}},rewrites:[{source:'/recipe/:slug',destination:'/index.html'},{source:'/delete-account',destination:'/index.html'},{source:'/privacy',destination:'/index.html'},{source:'/terms',destination:'/index.html'}],headers:[{source:'/(.*)',headers:[{key:'X-Content-Type-Options',value:'nosniff'},{key:'Referrer-Policy',value:'strict-origin-when-cross-origin'},{key:'Permissions-Policy',value:'camera=(), microphone=(), geolocation=(self)'},{key:'X-Frame-Options',value:'DENY'},{key:'Content-Security-Policy',value:"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co; worker-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'"}]},{source:'/service-worker.js',headers:[{key:'Cache-Control',value:'no-cache, no-store, must-revalidate'}]},{source:'/index.html',headers:[{key:'Cache-Control',value:'no-cache'}]}]},null,2));
await fs.mkdir('public/fonts',{recursive:true});
for(const [family,name] of [['Manrope','manrope'],['Fraunces','fraunces']]){
 const r=await fetch('https://fonts.googleapis.com/css2?family='+family+':wght@400;500;600;700&display=swap',{headers:{'User-Agent':'Mozilla/5.0 Chrome/130.0.0.0 Safari/537.36'}});if(!r.ok)throw Error('Font CSS unavailable');const css=await r.text();
 const latin=css.split('/* latin */').at(-1);const url=latin.match(/url\((https:[^)]+)\)/)?.[1];if(!url)throw Error('Latin font unavailable');
 const font=await fetch(url);if(!font.ok)throw Error('Font unavailable');await fs.writeFile('public/fonts/'+name+'.woff2',Buffer.from(await font.arrayBuffer()));
}
console.log('Shell, manifest, service worker and fonts written.');
