import {esc,uid,MEALS,CATEGORIES,dayKey,addDays,headcount,parseSearch,eligible,recommend,quantity,currency,vegetarianText} from './core.js';
import {cachedJSON,loadCategories,dishes} from './catalog.js';
import {dishPhoto,photoCredit} from './photos.js';
import {materializeRecurrences,parseAmount,consumptionSummary,portionLearning,householdTaste,productionSchedule,eventSchedule,substitutes} from './intelligence.js';
const button=(action,text,extra='')=>`<button type="button" class="secondary" data-extra="${action}" ${extra}>${text}</button>`;
const options=(values,current)=>values.map(v=>`<option ${String(v)===String(current)?'selected':''}>${esc(v)}</option>`).join('');
const regions={IND:['Rajasthani','Gujarati','Punjabi','North Indian','South Indian','Maharashtrian','Sindhi','Bengali','Kashmiri','Indian'],ITA:['Italian'],MEX:['Mexican'],THA:['Thai'],CHN:['Chinese','Indo-Chinese'],JPN:['Japanese-inspired'],GRC:['Mediterranean'],LBN:['Middle Eastern'],FRA:['French']};
const indianStates={Rajasthani:'Rajasthan',Gujarati:'Gujarat',Punjabi:'Punjab','South Indian':'Southern India',Maharashtrian:'Maharashtra',Sindhi:'Sindhi cuisine',Bengali:'West Bengal',Kashmiri:'Kashmir','North Indian':'Northern India',Indian:'Across India'};
export function installFeatures(ctx){
 let swipe=[],swipeIndex=0,recurrencePreview,eventPreview,photoPreview,recipePhoto,voice,dragStart;
 const owner=()=>ctx.user()?.id||null;
 const assertOwner=id=>{if(!id||id!==owner())throw Error('Your account changed. Open this action again.');};
 const save=async(id,kind,key,payload)=>{assertOwner(id);return ctx.put(kind,key,payload);};
 const loadAll=()=>loadCategories(CATEGORIES);
 const stored=(key,fallback)=>ctx.store()?.value(key,fallback)??fallback;
 function decorate(){
  const main=document.querySelector('#main');if(!main||main.querySelector('.feature-tools'))return;
  const view=ctx.view();let html='';
  if(view==='discover')html=button('map','Explore the food map')+button('swipe','Swipe for dinner')+button('assistant','Kitchen assistant')+button('new','Cook something new')+button('event','Plan an event');
  if(view==='planner')html=button('recurrences','Recurring menus')+button('shelf','Open dish shelf')+button('event','Event menus');
  if(view==='pantry')html=button('scan','Scan pantry photo')+button('consumption','Record food used or wasted');
  if(view==='insights')html=button('consumption','Record consumption')+button('portions','Record meal portions')+button('taste','Household tastes');
  if(view==='family')html=button('taste','Household tastes');
  if(view==='settings')html=button('capacity','Production capacity');
  if(html){const target=main.querySelector('.discover-tools,.calendar-toolbar,.page-heading')||main.firstElementChild;target.insertAdjacentHTML('afterend',`<div class="feature-tools">${html}</div>`);}
  if(view==='pantry')for(const row of main.querySelectorAll('.stock-row')){const id=row.querySelector('[data-id]')?.dataset.id;if(id)row.insertAdjacentHTML('beforeend',button('stock-log','Used / wasted',`data-id="${esc(id)}"`));}
  if(view==='insights'){
   const summary=consumptionSummary(ctx.store()?.get('consumption')||[]);
   main.insertAdjacentHTML('beforeend',`<section class="panel consumption-panel"><h2>Recorded food use</h2><p>${summary.used} use records · ${summary.wasted} waste records. Recorded value used ${currency(summary.valueUsed)}; wasted ${currency(summary.valueWasted)}.</p><p class="quiet-note">Values come only from entries you recorded. Used food is not automatically counted as money saved.</p>${summary.groups.map(x=>`<div class="rank-row"><b>${esc(x.name)}</b><span>Used ${quantity({qty:x.used,unit:x.unit})} · Wasted ${quantity({qty:x.wasted,unit:x.unit})}</span></div>`).join('')}</section>`);
  }
 }
 function decorateModal(){
  const root=document.querySelector('#dialogBody');if(!root)return;
  if(root.querySelector('.recipe-banner')&&!root.querySelector('.recipe-extras'))root.insertAdjacentHTML('beforeend',`<div class="recipe-extras button-row">${button('substitutions','Ingredient substitutes')}${button('recipe-photo','Add private recipe photo')}${button('share-recipe','Download recipe card')}</div>`);
  if(root.querySelector('.cooking-step')&&!root.querySelector('[data-extra="voice"]'))root.insertAdjacentHTML('beforeend',button('voice','Voice commands'));
  if(root.querySelector('.basket-row')&&!root.querySelector('[data-extra="production"]'))root.insertAdjacentHTML('beforeend',button('production','Production schedule'));
  if(root.querySelector('#customForm')&&!root.querySelector('#privatePhotoInput'))root.querySelector('#customForm').insertAdjacentHTML('beforeend','<label>Private recipe photograph (optional)<input type="file" id="privatePhotoInput" accept="image/jpeg,image/png,image/webp"><small>Saved only in your account; not sent to AI.</small></label>');
 }
 async function map(){const data=await cachedJSON('/data/world-map.json');ctx.modal('A world of vegetarian food',`<p>Choose a highlighted country, then a cuisine. The same headcount and food rules apply.</p><div class="food-map"><svg viewBox="0 0 720 330" role="img" aria-label="World cuisine map">${data.map(c=>`<path d="${c.path}" class="${regions[c.code]?'map-active':'map-land'}" ${regions[c.code]?`data-extra="country" data-code="${c.code}" tabindex="0" role="button" aria-label="Explore ${esc(c.name)}"`:''}><title>${esc(c.name)}</title></path>`).join('')}</svg></div><div class="cuisine-grid">${Object.keys(regions).map(code=>button('country',esc(data.find(c=>c.code===code)?.name||code),`data-code="${code}"`)).join('')}</div><p class="quiet-note">Map data: <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noopener">Natural Earth</a>, public domain. Regional menus represent cuisine traditions.</p>`);}
 function showSwipe(){const d=swipe[swipeIndex];if(!d)return ctx.modal('Your tasting tour is complete',`<p>Your choices are saved in your private kitchen.</p>${button('swipe','Start another round')}`);ctx.modal('A little yes. A little discovery.',`<p>${swipeIndex+1} of ${swipe.length} · Swipe right to like, left to skip. Buttons work too.</p><article id="swipeCard" class="swipe-card">${dishPhoto(d,true)}<h2>${esc(d.name)}</h2><p>${esc(d.cuisine)} · ${d.time} minutes</p></article><div class="button-row">${button('swipe-no','← Not today')}${button('swipe-recipe','View recipe')}${button('swipe-yes','Like →')}</div>`);}
 async function swipeChoice(like){const id=owner();assertOwner(id);const d=swipe[swipeIndex];if(!d)return;if(like)await save(id,'favorite','favorite:'+d.id,{dishId:d.id});else {const p=ctx.state().preferences[d.id]||{};await save(id,'preference','preference:'+d.id,{dishId:d.id,value:{...p,skipped:(p.skipped||0)+1}});}assertOwner(id);swipeIndex++;showSwipe();}
 function consumption(item){if(!ctx.requireUser())return;const x=item||{};ctx.modal('What happened to this food?',`<form data-feature-form="consumption"><input type="hidden" name="stockId" value="${esc(x._id||'')}"><label>Ingredient or leftover<input name="name" value="${esc(x.name||'')}" maxlength="100" required></label><label>Quantity used or wasted<input name="quantity" value="${esc(x.quantity||'')}" placeholder="300 g, 1.5 kg, 250 ml, 2 pieces" required></label><label>Outcome<select name="outcome"><option value="used">Used</option><option value="wasted">Wasted</option></select></label><label>Value of this quantity ₹ (optional)<input name="value" type="number" min="0" max="1000000" step="0.01"></label><label>Date<input name="date" type="date" value="${dayKey()}" required></label><p>Logging from pantry deducts this quantity from the stock entry. Use manual entry if the quantities are unknown.</p><button class="primary">Save food record</button></form>`);}
 async function recurring(){if(!ctx.requireUser())return;const rules=ctx.state().recurrences;ctx.modal('Menus that return',`<p>Save a calendar meal with “Repeat” to create a rule. Generate up to 90 days below. Occupied slots are kept. Main dishes still rest for 8 days, so a weekly rule may skip alternate weeks.</p>${rules.map(r=>`<div class="rank-row"><div><b>${esc(r.name)}</b><p>${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][r.weekday]} · ${esc(r.meal)} · ${r.enabled===false?'Paused':'Active'}</p></div>${button('recurrence-toggle',r.enabled===false?'Resume':'Pause',`data-id="${esc(r._id)}"`)}</div>`).join('')||'<p>No recurring menus yet. Add a meal from the calendar first.</p>'}<form data-feature-form="recurrences"><label>From<input type="date" name="from" value="${ctx.week()}" required></label><label>Days ahead<input type="number" name="days" min="1" max="90" value="28" required></label><button class="primary" ${rules.length?'':'disabled'}>Preview recurring calendar</button></form>`);}
 function capacity(){if(!ctx.requireUser())return;const s=stored('config:production',{});ctx.modal('Your production capacity',`<form data-feature-form="capacity"><label>Usable servings per vessel batch<input name="servingsPerBatch" type="number" min="1" max="100000" value="${s.servingsPerBatch||50}" required></label><label>Cooking stations<input name="stations" type="number" min="1" max="100" value="${s.stations||2}" required></label><label>Cooking staff available<input name="staff" type="number" min="1" max="1000" value="${s.staff||2}" required></label><label>Service hour (24-hour clock)<input name="serviceHour" type="number" min="0" max="23" value="${s.serviceHour??13}" required></label><p>Enter measured usable yield for your vessels. Schedules use the lower of this and the recipe batch limit.</p><button class="primary">Save capacity</button></form>`);}
 async function production(){const id=owner(),list=ctx.basket().map(x=>dishes.get(x)).filter(Boolean),recipes=await Promise.all(list.map(d=>ctx.recipeFor(d.id)));if(id!==owner())return;const result=productionSchedule(list,recipes,ctx.party(),stored('config:production',{}));ctx.modal('The plan behind the meal',`<p>${result.headcount.servings} servings · ${result.stations} active stations · ${Math.ceil(result.duration/60)} hours of production window.</p>${result.overnight?'<p class="notice">This schedule starts before the service day. Increase capacity or plan a supervisor-reviewed earlier production shift.</p>':''}<div class="table-scroll"><table><thead><tr><th>Dish</th><th>Batches</th><th>Station</th><th>Start</th><th>Finish</th></tr></thead><tbody>${result.jobs.map(j=>`<tr><td>${esc(j.name)}${j.passive?`<small>${esc(j.passive)}</small>`:''}</td><td>${j.batches}</td><td>${j.lane}</td><td>${j.startTime}</td><td>${j.finishTime}</td></tr>`).join('')}</tbody></table></div><p class="quiet-note">${esc(result.note)}</p>${button('capacity','Change capacity')}`);}
 async function event(){ctx.headcountDialog(async()=>{const account=owner(),all=await loadAll();if(account!==owner())return;eventPreview=eventSchedule(all,ctx.party(),ctx.filters(),ctx.state());ctx.modal('Every course has a place',`<p>${esc(ctx.party().eventType||'Event')} · ${headcount(ctx.party()).servings} servings · ${esc(ctx.party().service||'Buffet')}</p>${eventPreview.map((s,i)=>`<section class="panel"><h3>${esc(s.meal)}</h3>${s.dishes.map(d=>`<p><b>${esc(d.course)}</b> · ${esc(d.name)}</p>`).join('')}${s.missing.length?`<p class="notice">Open courses: ${s.missing.map(esc).join(', ')}. Food rules have been preserved.</p>`:''}${button('event-use','Use this menu',`data-index="${i}"`)}</section>`).join('')}`);});}
 async function shelf(){const all=await loadCategories(MEALS),eligibleRows=all.filter(d=>eligible(d,ctx.filters(),ctx.state())).slice(0,30);const old=document.querySelector('#dishShelf');if(old){old.remove();return;}document.querySelector('#main').insertAdjacentHTML('beforeend',`<section class="panel" id="dishShelf"><h2>Drag a dish into your week</h2><p>Drag on desktop, or use “Add to calendar” on any device.</p><div class="dish-shelf">${eligibleRows.map(d=>`<article draggable="true" data-dish="${esc(d.id)}">${dishPhoto(d)}<b>${esc(d.name)}</b><button class="text-btn" data-action="single-plan" data-id="${esc(d.id)}">Add to calendar</button></article>`).join('')}</div></section>`);}
 function assistant(scan=false){if(scan&&!ctx.requireUser())return;const enabled=ctx.config()?.ai;ctx.modal(scan?'A quick pantry check':'Tell your kitchen what you need',`<p>${scan?'Choose a photo of ingredients. AI suggestions need your review; a photo cannot establish freshness or allergen safety.':'Try “Dinner for six adults and three kids, Punjabi, under 30 minutes, without potato and onion”.'}</p><form data-feature-form="${scan?'scan':'assistant'}">${scan?'<label>Pantry photo<input id="scanFile" type="file" accept="image/jpeg,image/png,image/webp" required></label>':'<label>Your meal request<textarea name="text" rows="4" maxlength="1500" required></textarea></label>'}${enabled?`<label class="check-row"><input type="checkbox" name="cloudConsent" ${scan?'required':''}> Send ${scan?'this photo':'this request'} to OpenAI for AI assistance.</label><p class="quiet-note">Only the text or photo you submit is sent. Private kitchen records are not attached. Response storage is disabled; provider processing policies still apply.</p>`:scan?'<p class="notice">Photo scanning needs an operator-configured AI key and quota migration. You can enter ingredients manually now.</p>':'<p class="quiet-note">Standard language parsing is available now. Cloud AI has not been enabled by the operator.</p>'}<button class="primary" ${scan&&!enabled?'disabled':''}>${scan?'Identify ingredients':'Find meal ideas'}</button></form>`);}
 async function askAI(payload){const id=owner();assertOwner(id);const {data}=await ctx.client().auth.getSession();assertOwner(id);const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.session.access_token},body:JSON.stringify({...payload,consent:true})});const result=await r.json();assertOwner(id);if(!r.ok)throw Error(result.error);return result;}
 async function resizePrivatePhoto(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10000000)throw Error('Choose a JPEG, PNG or WebP smaller than 10 MB.');const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas'),ratio=Math.min(1,960/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.78);if(data.length>350000)throw Error('This photo is too detailed for private offline storage. Choose a smaller image.');return data;}finally{bitmap.close();}}
 async function cardDownload(){const r=ctx.activeRecipe();if(!r)return;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const g=canvas.getContext('2d');g.fillStyle='#f5f1e8';g.fillRect(0,0,1080,1350);g.fillStyle='#194b3d';g.fillRect(0,0,1080,90);g.fillStyle='#fff';g.font='28px Georgia';g.fillText('KAVITA KA KITCHEN',55,58);const d=dishes.get(r.id)||r;if(r.privatePhoto||d.photo?.src){const img=new Image();img.src=r.privatePhoto||d.photo.src;await img.decode();const ratio=Math.min(960/img.width,610/img.height);g.drawImage(img,(1080-img.width*ratio)/2,130,img.width*ratio,img.height*ratio);}g.fillStyle='#194b3d';g.font='bold 48px Georgia';let y=820;for(const line of wrap(r.name,33)){g.fillText(line,55,y);y+=60;}g.font='26px Arial';g.fillText('Vegetarian. Eggless. Made for a happier table.',55,y+15);g.font='23px Arial';g.fillText(r.privatePhoto||d.custom?'A private family recipe':location.origin+'/recipe/'+r.id,55,y+65);if(d.photo){g.font='18px Arial';for(const line of wrap('Photo: '+d.photo.author+' | '+d.photo.license,80)){g.fillText(line,55,1190);break;}g.fillText('Credit and licence: '+location.origin+'/recipe/'+r.id,55,1230);}const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kavita-kitchen-'+r.id+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const wrap=(text,n)=>String(text).match(new RegExp('.{1,'+n+'}(?:\\s|$)|.{1,'+n+'}','g'))||[];
 async function act(name,el){
  const id=owner();
  if(name==='map')return map();
  if(name==='country'){const codes=regions[el.dataset.code]||[];return ctx.modal('Choose a regional kitchen',`<div class="cuisine-grid">${codes.map(c=>button('cuisine',esc(el.dataset.code==='IND'?indianStates[c]+' · '+c:c),`data-cuisine="${esc(c)}"`)).join('')}</div>`);}
  if(name==='cuisine')return ctx.search({cuisine:el.dataset.cuisine,category:'Dinner',query:''});
  if(name==='swipe'){if(!ctx.requireUser())return;return ctx.headcountDialog(async()=>{const all=await loadAll();assertOwner(id);swipe=recommend(all,ctx.filters(),ctx.state()).slice(0,20);swipeIndex=0;showSwipe();});}
  if(name==='swipe-yes'||name==='swipe-no')return swipeChoice(name==='swipe-yes');
  if(name==='swipe-recipe')return ctx.openRecipe(swipe[swipeIndex]?.id);
  if(name==='new')return ctx.search({newOnly:true,query:''});
  if(name==='recurrences')return recurring();
  if(name==='recurrence-toggle'){assertOwner(id);const r=ctx.state().recurrences.find(r=>r._id===el.dataset.id);await save(id,'recurrence',r._id,{...r,enabled:r.enabled===false});return recurring();}
  if(name==='recurrence-apply'){assertOwner(id);if(!recurrencePreview||recurrencePreview.owner!==id)throw Error('Preview these menus again.');const fresh=materializeRecurrences([...dishes.values()],ctx.state().recurrences,recurrencePreview.from,recurrencePreview.days,ctx.filters(),ctx.state());for(const p of fresh.created)await save(id,'plan','plan:'+p.date+':'+p.meal,p);recurrencePreview=null;ctx.close();ctx.nav('planner');ctx.notify('Recurring menus saved.');return;}
  if(name==='capacity')return capacity();if(name==='production')return production();if(name==='event')return event();if(name==='shelf')return shelf();
  if(name==='event-use'){ctx.setBasket(eventPreview?.[Number(el.dataset.index)]?.dishes.map(d=>d.id)||[]);return ctx.openBasket();}
  if(name==='consumption')return consumption();
  if(name==='stock-log')return consumption([...ctx.state().pantry,...ctx.state().leftovers].find(x=>x._id===el.dataset.id));
  if(name==='portions'){if(!ctx.requireUser())return;await loadAll();assertOwner(id);return ctx.modal('Learn your serving sizes',`<form data-feature-form="portions"><label>Dish<select name="dishId">${[...dishes.values()].filter(d=>!d.custom).map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label><label>People who ate<input name="people" type="number" min="1" max="100000" required></label><label>Adult portions prepared<input name="prepared" type="number" min="0.1" max="100000" step="0.1" required></label><label>Adult portions actually eaten<input name="eaten" type="number" min="0" max="100000" step="0.1" required></label><button class="primary">Save portion record</button></form>`);}
  if(name==='taste'){if(!ctx.requireUser())return;const all=await loadAll();assertOwner(id);const list=householdTaste(all.filter(d=>eligible(d,ctx.filters(),ctx.state())),ctx.state());return ctx.modal('A seat for every taste',list.map(({person,scored})=>`<section class="panel"><h3>${esc(person.name)}${person.child?' · Kids':''}</h3>${scored.map(x=>`<div class="rank-row"><b>${esc(x.dish.name)}</b><meter min="0" max="20" value="${Math.min(20,x.score)}" aria-label="Preference match ${x.score}"></meter></div>`).join('')||'<p>Add likes, cuisines and votes to discover matches.</p>'}</section>`).join('')||'<p>Add family profiles to build your household taste view.</p>');}
  if(name==='assistant')return assistant();if(name==='scan')return assistant(true);
  if(name==='scan-save'){assertOwner(id);if(photoPreview?.owner!==id)throw Error('Scan again in this account.');const selected=[...document.querySelectorAll('[name="scanIngredient"]:checked')].map(el=>el.value);for(const ingredient of selected)await save(id,'pantry','pantry:'+uid(),{name:ingredient,quantity:'',expiry:null,source:'reviewed-photo'});photoPreview=null;ctx.close();ctx.nav('pantry');return;}
  if(name==='substitutions'){const r=ctx.activeRecipe(),d=dishes.get(r?.id);if(!d)return;return ctx.modal('A thoughtful swap',`<p>These options respect your saved exclusions. Adjust taste and texture; they are not guaranteed one-for-one replacements. Check the actual product label.</p>${r.ingredients.map(i=>{const list=substitutes(i.name,d,ctx.filters(),ctx.state());return list.length?`<div class="rank-row"><b>${esc(i.name)}</b><span>${list.map(esc).join(' / ')}</span></div>`:'';}).join('')||'<p>No checked substitutions are available for this recipe.</p>'}`);}
  if(name==='recipe-photo'){const r=ctx.activeRecipe();if(!ctx.requireUser())return;if(!r||!ctx.state().custom.some(x=>x.id===r.id))throw Error('Photographs can be attached to your private family recipes. Open one from the recipe vault.');recipePhoto=r;return ctx.modal('A photo for your family recipe','<form data-feature-form="recipe-photo"><label>Food photograph<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required></label><p>Stored only in your private account, with no AI processing.</p><button class="primary">Save private photo</button></form>');}
  if(name==='share-recipe')return cardDownload();
  if(name==='voice'){if(voice){voice.stop();voice=null;ctx.notify('Voice commands stopped.');return;}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech)throw Error('Voice input is unavailable in this browser. Next, Previous and Repeat buttons remain available.');ctx.modal('Hands-free cooking',`<p>Your browser may send speech to its recognition service. Start only when you want microphone input. Supported commands: next step, previous step, repeat step, and set timer 8 minutes.</p>${button('voice-start','Start microphone')}`);return;}
  if(name==='voice-start'){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;voice=new Speech();voice.lang='en-IN';voice.continuous=true;voice.onresult=e=>{const words=e.results[e.results.length-1][0].transcript.toLowerCase();if(/next/.test(words))ctx.cookingAction('step-next');else if(/previous|back/.test(words))ctx.cookingAction('step-prev');else if(/repeat/.test(words))ctx.cookingAction('step-repeat');else {const m=words.match(/timer\s+(\d+)\s*min/);if(m&&+m[1]>0&&+m[1]<=240)ctx.addTimer('Voice timer',+m[1]);}};voice.onerror=()=>ctx.notify('Voice input stopped. Use the cooking buttons.');voice.onend=()=>voice=null;voice.start();ctx.showCooking();return;}
 }
 async function submit(form){const id=owner(),f=new FormData(form),v=Object.fromEntries(f);const key=form.dataset.featureForm;
  if(key==='assistant'){const local=parseSearch(v.text),result=f.has('cloudConsent')?(await askAI({mode:'search',text:v.text})).filters:local;return ctx.search({...result,exclusions:[...new Set([...(result.exclusions||[]),...local.exclusions,...(ctx.filters().exclusions||[])])],jain:result.jain||local.jain||ctx.filters().jain});}
  assertOwner(id);
  if(key==='recurrences'){const all=await loadAll();assertOwner(id);recurrencePreview={...materializeRecurrences(all,ctx.state().recurrences,v.from,Number(v.days),ctx.filters(),ctx.state()),owner:id,from:v.from,days:Number(v.days)};return ctx.modal('Your recurring calendar preview',`<p>${recurrencePreview.created.length} new meals · ${recurrencePreview.skipped.length} skipped for rotation or food rules.</p><div class="recurrence-list">${recurrencePreview.created.map(p=>`<p><b>${p.date} · ${esc(p.meal)}</b> ${esc(p.name)}</p>`).join('')}${recurrencePreview.skipped.map(p=>`<p class="quiet-note">Skipped ${p.date} · ${esc(p.name)}: ${esc(p.reason)}</p>`).join('')}</div>${button('recurrence-apply','Save these meals')}`);}
  if(key==='capacity'){const payload=Object.fromEntries(Object.entries(v).map(([k,x])=>[k,Number(x)]));productionSchedule([],[],ctx.party(),payload);await save(id,'config','config:production',payload);ctx.close();ctx.notify('Production capacity saved.');return;}
  if(key==='consumption'){if(!vegetarianText(v.name))throw Error('Use vegetarian, eggless ingredients.');const amount=parseAmount(v.quantity);if(!amount)throw Error('Enter a measurable quantity, for example 300 g or 1.5 kg.');const stock=[...ctx.state().pantry,...ctx.state().leftovers].find(x=>x._id===v.stockId),available=stock&&parseAmount(stock.quantity);if(stock&&(!available||available.unit!==amount.unit||amount.qty>available.qty))throw Error('Use the same unit and no more than the recorded stock. Correct the stock quantity first.');const value=Number(v.value||0);if(!Number.isFinite(value)||value<0)throw Error('Enter a valid value.');await save(id,'consumption','consumption:'+uid(),{name:v.name.trim(),...amount,outcome:v.outcome,value,date:v.date});if(stock){const left=+(available.qty-amount.qty).toFixed(2);await save(id,stock._id.startsWith('leftover:')?'leftover':'pantry',stock._id,{...stock,quantity:left+' '+amount.unit});}ctx.close();ctx.nav('insights');return;}
  if(key==='portions'){const prepared=Number(v.prepared),eaten=Number(v.eaten),people=Number(v.people);if(!Number.isFinite(prepared)||!Number.isFinite(eaten)||!Number.isFinite(people)||prepared<=0||eaten<0||eaten>prepared||people<=0)throw Error('Eaten portions must be between zero and the portions prepared.');await save(id,'consumption','consumption:'+uid(),{dishId:v.dishId,prepared,eaten,people,date:dayKey()});const learned=portionLearning(ctx.store().get('consumption'),v.dishId);ctx.modal('A little more understanding',`<p>${learned?`From ${learned.samples} records, your household averages ${learned.portionsPerPerson.toFixed(2)} adult portions per person for this dish.`:'Record this dish on three occasions to see a serving estimate.'}</p><p>Headcount and buffers remain under your control.</p>`);return;}
  if(key==='scan'){const photo=await resizePrivatePhoto(f.get('scanFile')||document.querySelector('#scanFile').files[0]);assertOwner(id);const result=await askAI({mode:'vision',image:photo});photoPreview={owner:id,ingredients:result.ingredients};ctx.modal('Check before adding',`<p>Select only ingredients you can confirm. Set quantities and dates manually.</p>${result.ingredients.map(x=>`<label class="check-row"><input type="checkbox" name="scanIngredient" value="${esc(x)}">${esc(x)}</label>`).join('')||'<p>No ingredients were identified clearly.</p>'}${button('scan-save','Add selected ingredients')}`);return;}
  if(key==='recipe-photo'){const photo=await resizePrivatePhoto(f.get('photo'));assertOwner(id);await save(id,'recipe','recipe:'+recipePhoto.id,{...recipePhoto,privatePhoto:photo});recipePhoto=null;ctx.close();ctx.notify('Private recipe photograph saved.');}
 }
 document.addEventListener('click',e=>{const el=e.target.closest('[data-extra]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();Promise.resolve(act(el.dataset.extra,el)).catch(ctx.error);},true);
 document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('path[data-extra]')){e.preventDefault();act(e.target.dataset.extra,e.target).catch(ctx.error);}});
 document.addEventListener('submit',e=>{const form=e.target;if(!form.dataset.featureForm)return;e.preventDefault();e.stopImmediatePropagation();const btn=form.querySelector('button[type="submit"],button.primary');if(btn)btn.disabled=true;submit(form).catch(ctx.error).finally(()=>{if(btn?.isConnected)btn.disabled=false;});},true);
 document.addEventListener('pointerdown',e=>{if(e.target.closest('#swipeCard'))dragStart={x:e.clientX,y:e.clientY};});
 document.addEventListener('pointerup',e=>{if(!dragStart)return;const dx=e.clientX-dragStart.x,dy=e.clientY-dragStart.y;dragStart=null;if(Math.abs(dx)>85&&Math.abs(dx)>Math.abs(dy)*1.5)swipeChoice(dx>0).catch(ctx.error);});
 return {decorate,decorateModal,resizePrivatePhoto,reset(){voice?.stop();voice=null;swipe=[];swipeIndex=0;recurrencePreview=null;eventPreview=null;photoPreview=null;recipePhoto=null;}};
}
