import {currency,esc,headcount,slug} from './core.js';

export function buildMenuProposal({name,client,date,service,notes,pricePerGuest,party,dishes,translate=String,language='en'}){
 if(!Array.isArray(dishes)||!dishes.length)throw Error('Add dishes before exporting a menu.');
 const h=headcount(party),price=pricePerGuest===''||pricePerGuest==null?null:Number(pricePerGuest);
 if(price!==null&&(!Number.isFinite(price)||price<0||price>1000000))throw Error('Enter a valid price per guest, or leave it blank.');
 const title=String(name||'Your menu').trim().slice(0,100);
 const tr=value=>esc(translate(value));
 const rows=dishes.map(d=>`<li>${esc(d.name)}</li>`).join('');
 const quote=price===null?'':`<section class="quote"><span>${tr('Quoted price per guest')}</span><strong>${currency(price)}</strong><span>${h.total} ${tr('guests')}</span><strong>${currency(price*h.total)} ${tr('total')}</strong></section>`;
 const html=`<!doctype html><html lang="${esc(language)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Kavita ka Kitchen</title><style>body{font:16px/1.6 system-ui,sans-serif;color:#183e34;background:#f6f5ef;margin:0}main{max-width:760px;margin:48px auto;background:#fff;padding:48px;border-radius:24px;box-shadow:0 12px 40px #163a2c18}header{border-bottom:2px solid #e2e8df;padding-bottom:24px}small{letter-spacing:.16em;text-transform:uppercase;color:#63786e}h1{font:600 42px/1.1 Georgia,serif;margin:14px 0}h2{font:600 25px Georgia,serif}ul{columns:2;padding-left:22px}li{break-inside:avoid;padding:4px 0}.meta{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin:28px 0}.meta div,.quote{background:#f5f7f0;padding:14px;border-radius:12px}.quote{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:28px}.note{white-space:pre-wrap}footer{border-top:1px solid #e2e8df;margin-top:30px;padding-top:18px;color:#55685f;font-size:13px}@media print{body{background:#fff}main{margin:0;max-width:none;box-shadow:none;padding:12mm}}@media(max-width:600px){main{margin:0;padding:24px;border-radius:0}.meta{grid-template-columns:1fr}ul{columns:1}}</style></head><body><main><header><small>${tr('Kavita ka Kitchen · Menu proposal')}</small><h1>${esc(title)}</h1>${client?`<p>${tr('Prepared for')} ${esc(String(client).slice(0,100))}</p>`:''}</header><div class="meta"><div><small>${tr('Service date')}</small><br>${esc(date||translate('To be agreed'))}</div><div><small>${tr('Guests')}</small><br>${h.total} ${tr('people')}${h.buffer?` · ${h.servings} ${tr('prepared including buffer')}`:''}</div><div><small>${tr('Kitchen')}</small><br>${tr(party.mode==='event'?'Event / Catering':party.mode==='factory'?'Factory Canteen':'Office Kitchen')}</div><div><small>${tr('Service style')}</small><br>${esc(service||party.service||translate('To be agreed'))}</div></div><h2>${tr('The menu')}</h2><ul>${rows}</ul>${notes?`<h2>${tr('Notes')}</h2><p class="note">${esc(String(notes).slice(0,2000))}</p>`:''}${quote}<footer>${tr(price===null?'Menu proposal only; pricing to be agreed.':'Price shown is an estimate until confirmed by the kitchen and client.')} ${tr('Confirm ingredients, dietary needs, service, taxes and final terms before ordering.')} ${tr('Generated')} ${new Date().toLocaleDateString(language==='gu'?'gu-IN':language==='hi'?'hi-IN':'en-IN')}.</footer></main></body></html>`;
 return {html,filename:`kavita-menu-${slug(title)||'proposal'}.html`,total:price===null?null:price*h.total};
}
