import fs from 'node:fs/promises';

const entries = [];
const add = (id, name, hi, gu, cuisine, mins, ingredients, steps, tip, url) => entries.push({id,name,hi,gu,cuisine,mins,ingredients,steps,tip,url});

add('doddapatre-bajji','Doddapatre Bajji','डोड्डपत्रे बज्जी','દોડ્ડપત્રે ભજી','Karnataka',30,[
 ['Indian borage leaves',160,'g','अजवाइन के पत्ते','અજમાના પાન'],['gram flour',150,'g','बेसन','ચણાનો લોટ'],['rice flour',35,'g','चावल का आटा','ચોખાનો લોટ'],['red chilli powder',4,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['carom seeds',3,'g','अजवाइन','અજમો'],['turmeric powder',2,'g','हल्दी','હળદર'],['salt',6,'g','नमक','મીઠું'],['water',190,'ml','पानी','પાણી'],['oil for frying',500,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Wash and dry the borage leaves thoroughly. Keep each leaf whole and trim only the toughest stem.','अजवाइन के पत्ते धोकर पूरी तरह सुखाएँ। हर पत्ता साबुत रखें और केवल सख्त डंठल काटें।','અજમાના પાન ધોઈને સંપૂર્ણ સુકવો. દરેક પાન આખું રાખો અને માત્ર કઠણ દાંડી કાપો.'],
 ['Whisk gram flour, rice flour, chilli, carom, turmeric and salt. Gradually add water to make a smooth batter that coats a leaf without running off.','बेसन, चावल का आटा, मिर्च, अजवाइन, हल्दी और नमक फेंटें। धीरे-धीरे पानी मिलाकर ऐसा चिकना घोल बनाएँ जो पत्ते पर टिके।','ચણાનો લોટ, ચોખાનો લોટ, મરચું, અજમો, હળદર અને મીઠું ફેંટો. ધીમે ધીમે પાણી ઉમેરી પાન પર ચોંટી રહે એવું લીસું ખીરું બનાવો.'],
 ['Heat oil over medium heat. Dip one leaf at a time, coat both sides thinly and lower carefully into the oil.','तेल मध्यम आँच पर गरम करें। एक-एक पत्ता घोल में दोनों ओर से पतला लपेटकर सावधानी से तेल में डालें।','તેલ મધ્યમ તાપે ગરમ કરો. એક એક પાનને ખીરામાં બંને બાજુ પાતળું ઢાંકી સાવધાનીથી તેલમાં નાખો.'],
 ['Fry in small batches, turning once, until the leaf-shaped fritters are golden and crisp; drain on a rack.','थोड़े-थोड़े पत्ते तलें, बीच में एक बार पलटें; सुनहरे और कुरकुरे होने पर जाली पर निकालें।','થોડાં થોડાં પાન તળો, વચ્ચે એક વાર ફેરવો; સોનેરી અને કરકરા થાય ત્યારે જાળી પર કાઢો.'],
 ['Serve immediately with coconut chutney while the leaf centres are tender and the batter stays crisp.','पत्तों के बीच का भाग नरम और बाहर का घोल कुरकुरा रहते नारियल की चटनी के साथ तुरंत परोसें।','પાનનો મધ્ય ભાગ નરમ અને બહારનું ખીરું કરકરું હોય ત્યારે નાળિયેરની ચટણી સાથે તરત પીરસો.']
],['Dry leaves prevent the batter from sliding off; do not pile the fried bajji while hot.','सूखे पत्तों पर घोल अच्छी तरह टिकता है; गरम बज्जी को एक-दूसरे पर न रखें।','સૂકા પાન પર ખીરું સારી રીતે ચોંટે છે; ગરમ ભજીને એકબીજા પર ઢગલો ન કરો.'],'https://www.sahajaseeds.com/wp-content/uploads/2025/02/SOPPU-CALENDAR-2025.pdf');

add('ulli-vada','Ulli Vada','उल्ली वड़ा','ઉલ્લી વડા','Kerala',40,[
 ['red onions, thinly sliced',400,'g','लाल प्याज, पतले कटे','લાલ ડુંગળી, પાતળી સમારેલી'],['gram flour',120,'g','बेसन','ચણાનો લોટ'],['rice flour',60,'g','चावल का आटा','ચોખાનો લોટ'],['ginger, grated',15,'g','कसा अदरक','છીણેલું આદુ'],['green chillies, chopped',12,'g','कटी हरी मिर्च','સમારેલાં લીલાં મરચાં'],['curry leaves, chopped',10,'g','कटे करी पत्ते','સમારેલાં મીઠા લીમડાનાં પાન'],['red chilli powder',3,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['salt',7,'g','नमक','મીઠું'],['water',50,'ml','पानी','પાણી'],['oil for frying',550,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Separate the onion slices with your fingers. Toss with salt and leave briefly so the onions release a little moisture.','प्याज के लच्छे उँगलियों से अलग करें। नमक मिलाकर कुछ देर रखें ताकि प्याज हल्का पानी छोड़े।','ડુંગળીના પાતળા પડ આંગળીઓથી છૂટા કરો. મીઠું ભેળવી થોડી વાર રાખો જેથી ડુંગળી થોડો રસ છોડે.'],
 ['Mix in ginger, green chillies, curry leaves, chilli powder, gram flour and rice flour. Rub the flours through the onions rather than making a thick smooth batter.','अदरक, हरी मिर्च, करी पत्ते, मिर्च पाउडर, बेसन और चावल का आटा मिलाएँ। गाढ़ा चिकना घोल बनाने के बजाय आटा प्याज में मलें।','આદુ, લીલાં મરચાં, મીઠા લીમડાનાં પાન, મરચું પાઉડર, ચણાનો અને ચોખાનો લોટ ભેળવો. ઘટ્ટ લીસું ખીરું બનાવવાને બદલે લોટ ડુંગળીમાં ચોળો.'],
 ['Sprinkle in just enough water for the onion strands to cling loosely together. Heat oil over medium heat.','प्याज के लच्छे बस हल्के जुड़ें इतना ही पानी छिड़कें। तेल मध्यम आँच पर गरम करें।','ડુંગળીના તાર ઢીલા જોડાઈ રહે એટલું જ પાણી છાંટો. તેલ મધ્યમ તાપે ગરમ કરો.'],
 ['Drop loose small handfuls into the oil without squeezing them into dense balls. Fry in batches until deep golden, turning for even colour.','मुट्ठीभर मिश्रण बिना दबाकर तेल में छोड़ें। थोड़ा-थोड़ा तलें और पलटते हुए गहरा सुनहरा करें।','નાની મુઠ્ઠી મિશ્રણ દબાવ્યા વગર તેલમાં છોડો. થોડું થોડું તળો અને ફેરવતાં ઘેરું સોનેરી કરો.'],
 ['Drain on a rack and serve hot with coconut chutney; the rice flour should make the onion edges distinctly crisp.','जाली पर निकालकर नारियल चटनी के साथ गरम परोसें; चावल के आटे से प्याज के किनारे कुरकुरे होने चाहिए।','જાળી પર કાઢી નાળિયેરની ચટણી સાથે ગરમ પીરસો; ચોખાના લોટથી ડુંગળીની કિનારીઓ કરકરી થવી જોઈએ.']
],['If the mixture becomes wet, dust with a little more rice flour instead of packing the fritters tightly.','मिश्रण गीला हो जाए तो वड़ों को दबाने के बजाय थोड़ा और चावल का आटा लगाएँ।','મિશ્રણ ભીનું થઈ જાય તો વડા દબાવવાને બદલે થોડો વધુ ચોખાનો લોટ છાંટો.'],'https://www.vegrecipesofindia.com/ulli-vada-recipe/');

add('kuzhalappam','Kuzhalappam','कुज़लप्पम','કુઝલપ્પમ','Kerala',65,[
 ['rice flour',300,'g','चावल का आटा','ચોખાનો લોટ'],['fresh grated coconut',100,'g','ताज़ा कसा नारियल','તાજું છીણેલું નાળિયેર'],['shallots',50,'g','छोटे प्याज','નાની ડુંગળી'],['garlic cloves',15,'g','लहसुन की कलियाँ','લસણની કળીઓ'],['cumin seeds',5,'g','जीरा','જીરું'],['white sesame seeds',18,'g','सफ़ेद तिल','સફેદ તલ'],['salt',7,'g','नमक','મીઠું'],['water',310,'ml','पानी','પાણી'],['coconut oil for frying',650,'ml','तलने का नारियल तेल','તળવા માટે નાળિયેરનું તેલ']
],[
 ['Grind coconut, shallots, garlic and cumin with part of the measured water; strain to obtain a strongly flavoured liquid.','नारियल, छोटे प्याज, लहसुन और जीरा दिए पानी के कुछ भाग के साथ पीसें; छानकर सुगंधित रस लें।','નાળિયેર, નાની ડુંગળી, લસણ અને જીરું આપેલા પાણીના થોડા ભાગ સાથે પીસો; ગાળીને સુગંધિત રસ લો.'],
 ['Bring that liquid and remaining water to a simmer with salt. Turn off heat and stir in rice flour and sesame to make a soft, non-sticky dough.','उस रस और बचे पानी में नमक डालकर गरम करें। आँच बंद कर चावल का आटा और तिल मिलाएँ; नरम, न चिपकने वाला आटा बनाएँ।','તે રસ અને બાકીનું પાણી મીઠા સાથે ઉકળાવો. તાપ બંધ કરી ચોખાનો લોટ અને તલ ભેળવી નરમ, ન ચોંટે એવો લોટ બનાવો.'],
 ['Cover until warm, then knead smooth. Roll small portions between oiled sheets into thin circles.','ढककर गुनगुना होने दें, फिर चिकना गूँधें। छोटे भाग तेल लगी चादरों के बीच पतले गोल बेलें।','ઢાંકીને હૂંફાળું થાય ત્યારે લીસું મસળો. નાના ભાગને તેલ લગાડેલી ચાદરો વચ્ચે પાતળા ગોળ વણો.'],
 ['Wrap each disc around an oiled narrow handle or tube and seal the overlap with water; slide off gently, keeping the hollow centre open.','हर गोल को तेल लगे पतले बेलन या नली पर लपेटें, जोड़ पानी से चिपकाएँ; बीच खोखला रखते हुए धीरे निकालें।','દરેક ગોળને તેલ લગાડેલા પાતળા વેલણ કે નળી પર વીંટો, સાંધો પાણીથી ચોંટાડો; મધ્યનો પોલો ભાગ ખુલ્લો રાખીને હળવે ઉતારો.'],
 ['Fry the tubes in medium-hot coconut oil until lightly golden and crisp throughout. Drain, cool completely and store airtight.','नलियों को मध्यम गरम नारियल तेल में हल्का सुनहरा और पूरी तरह कुरकुरा तलें। निकालकर पूरा ठंडा करें और बंद डिब्बे में रखें।','નળીઓને મધ્યમ ગરમ નાળિયેરના તેલમાં હળવી સોનેરી અને પૂરેપૂરી કરકરી તળો. કાઢી સંપૂર્ણ ઠંડી કરી હવાચુસ્ત ડબ્બામાં રાખો.']
],['A stiff or dry dough cracks while rolling; knead in a few drops of warm water if needed.','कड़ा या सूखा आटा बेलते समय फटता है; ज़रूरत हो तो गर्म पानी की कुछ बूँदें मिलाएँ।','કઠણ કે સૂકો લોટ વણતાં તૂટે છે; જરૂર પડે તો હૂંફાળા પાણીનાં થોડાં ટીપાં ભેળવો.'],'https://www.cheenachatti.com/recipe/kuzhalappam/');

add('corn-pakoda','Corn Pakoda','कॉर्न पकोड़ा','મકાઈના પકોડા','Pan-Indian',35,[
 ['sweet corn kernels',400,'g','मीठे मक्के के दाने','મીઠી મકાઈના દાણા'],['gram flour',130,'g','बेसन','ચણાનો લોટ'],['rice flour',35,'g','चावल का आटा','ચોખાનો લોટ'],['red onion, chopped',100,'g','कटा लाल प्याज','સમારેલી લાલ ડુંગળી'],['green chillies, chopped',12,'g','कटी हरी मिर्च','સમારેલાં લીલાં મરચાં'],['ginger, grated',15,'g','कसा अदरक','છીણેલું આદુ'],['coriander leaves',20,'g','हरा धनिया','લીલી કોથમીર'],['red chilli powder',4,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['salt',8,'g','नमक','મીઠું'],['water',35,'ml','पानी','પાણી'],['oil for frying',550,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Roughly crush a third of the corn kernels and leave the rest whole. Pat the kernels dry to keep the pakoda crisp.','मक्के के लगभग एक तिहाई दाने मोटे कूटें, बाकी साबुत रखें। कुरकुरापन बनाए रखने के लिए दाने सुखाएँ।','મકાઈના લગભગ ત્રીજા ભાગના દાણા અધકચરા વાટો, બાકીના આખા રાખો. પકોડા કરકરા રહે માટે દાણા સુકવો.'],
 ['Combine corn, onion, chillies, ginger, coriander, chilli powder and salt. Mix in gram flour and rice flour until every kernel is coated.','मक्का, प्याज, मिर्च, अदरक, धनिया, मिर्च पाउडर और नमक मिलाएँ। बेसन और चावल का आटा मिलाकर हर दाने पर लपेटें।','મકાઈ, ડુંગળી, મરચાં, આદુ, કોથમીર, મરચું પાઉડર અને મીઠું ભેળવો. ચણાનો અને ચોખાનો લોટ ઉમેરી દરેક દાણાને ઢાંકો.'],
 ['Sprinkle only enough water to bind small rough clusters; do not make a pourable batter. Heat oil over medium heat.','बस छोटे अनगढ़ गोले जुड़ें इतना पानी छिड़कें; बहता हुआ घोल न बनाएँ। तेल मध्यम आँच पर गरम करें।','માત્ર નાના ખરબચડા ગૂંચા બંધાય એટલું પાણી છાંટો; રેડી શકાય એવું ખીરું ન બનાવો. તેલ મધ્યમ તાપે ગરમ કરો.'],
 ['Drop small spoonfuls into the oil. Fry without crowding, turning until the corn is cooked and the exterior is evenly golden.','चम्मच से छोटे हिस्से तेल में डालें। भीड़ न करें; पलटते हुए मक्का पकने और बाहर एकसार सुनहरा होने तक तलें।','ચમચીથી નાના ભાગ તેલમાં નાખો. ભીડ ન કરો; ફેરવતાં મકાઈ રંધાય અને બહાર એકસરખું સોનેરી થાય ત્યાં સુધી તળો.'],
 ['Drain on a rack, dust lightly with chaat masala if desired and serve at once with green chutney.','जाली पर निकालें, चाहें तो हल्का चाट मसाला छिड़कें और हरी चटनी के साथ तुरंत परोसें।','જાળી પર કાઢો, ઇચ્છો તો થોડું ચાટ મસાલું છાંટો અને લીલી ચટણી સાથે તરત પીરસો.']
],['A little crushed corn acts as a binder while whole kernels give each pakoda its signature bite.','कुछ कुटे दाने मिश्रण बाँधते हैं और साबुत दाने पकोड़े को खास बनावट देते हैं।','થોડા વાટેલા દાણા મિશ્રણ બાંધે છે અને આખા દાણા પકોડાને ખાસ મજા આપે છે.'],'https://hebbarskitchen.com/corn-pakoda-recipe-corn-bhajiya/');

add('echorer-chop','Echorer Chop','एँचोर चॉप','એંચોર ચોપ','Bengali',65,[
 ['raw tender jackfruit, cleaned',400,'g','साफ़ कच्चा कटहल','સાફ કરેલું કાચું ફણસ'],['potatoes',300,'g','आलू','બટાકા'],['red onion, finely chopped',100,'g','बारीक कटा लाल प्याज','બારીક સમારેલી લાલ ડુંગળી'],['ginger paste',18,'g','अदरक पेस्ट','આદુની પેસ્ટ'],['green chillies, chopped',12,'g','कटी हरी मिर्च','સમારેલાં લીલાં મરચાં'],['roasted cumin powder',5,'g','भुना जीरा पाउडर','શેકેલા જીરાનો પાઉડર'],['garam masala',4,'g','गरम मसाला','ગરમ મસાલો'],['breadcrumbs',150,'g','ब्रेड का चूरा','બ્રેડનો ભૂકો'],['cornflour',45,'g','कॉर्नफ्लोर','કોર્નફ્લોર'],['water',100,'ml','पानी','પાણી'],['salt',9,'g','नमक','મીઠું'],['oil for frying',600,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Oil your hands and knife before handling jackfruit. Steam the jackfruit until tender, boil potatoes separately and drain both thoroughly.','कटहल काटने से पहले हाथ और चाकू पर तेल लगाएँ। कटहल नरम होने तक भाप में पकाएँ, आलू अलग उबालें और दोनों का पानी पूरी तरह निकालें।','ફણસ કાપતાં પહેલાં હાથ અને ચાકૂ પર તેલ લગાવો. ફણસ નરમ થાય ત્યાં સુધી બાફો, બટાકા અલગ બાફો અને બંનેનું પાણી સંપૂર્ણ કાઢો.'],
 ['Shred the jackfruit and mash the potatoes. Cook onion, ginger and chilli in a little oil until aromatic, then add jackfruit, cumin, garam masala and salt.','कटहल रेशा-रेशा करें और आलू मसलें। थोड़े तेल में प्याज, अदरक और मिर्च महकने तक भूनें; कटहल, जीरा, गरम मसाला और नमक मिलाएँ।','ફણસના રેસા કરો અને બટાકા મસળો. થોડા તેલમાં ડુંગળી, આદુ અને મરચાં સુગંધ આવે ત્યાં સુધી સાંતળો; ફણસ, જીરું, ગરમ મસાલો અને મીઠું ઉમેરો.'],
 ['Cook the filling until dry; fold in potato and cool completely. Shape into firm oval chops.','भरावन सूखने तक पकाएँ; आलू मिलाकर पूरा ठंडा करें। दबाकर अंडाकार चॉप बनाएँ।','પૂરણ સુકાય ત્યાં સુધી રાંધો; બટાકા ભેળવી સંપૂર્ણ ઠંડું કરો. દબાવી અંડાકાર ચોપ બનાવો.'],
 ['Whisk cornflour with water into a thin slurry. Dip each chop and coat all sides evenly with breadcrumbs; chill until the coating sets.','कॉर्नफ्लोर और पानी का पतला घोल फेंटें। हर चॉप डुबोकर चारों ओर ब्रेड का चूरा लगाएँ; परत जमने तक ठंडा करें।','કોર્નફ્લોર અને પાણીનું પાતળું ખીરું ફેંટો. દરેક ચોપ ડુબાડી ચારે બાજુ બ્રેડનો ભૂકો લગાવો; પડ ચોંટે ત્યાં સુધી ઠંડું કરો.'],
 ['Fry in medium-hot oil in small batches until crisp and deep golden. Drain well and serve with Bengali mustard relish.','मध्यम गरम तेल में थोड़े-थोड़े चॉप कुरकुरे और गहरे सुनहरे तलें। अच्छी तरह छानकर बंगाली सरसों चटनी के साथ परोसें।','મધ્યમ ગરમ તેલમાં થોડા થોડા ચોપ કરકરા અને ઘેરા સોનેરી તળો. સારી રીતે નિતારી બંગાળી સરસવની ચટણી સાથે પીરસો.']
],['The filling must be dry and cool before shaping or the croquettes will split in oil.','आकार देने से पहले भरावन सूखा और ठंडा होना चाहिए, नहीं तो चॉप तेल में फटेंगे।','આકાર આપતાં પહેલાં પૂરણ સુકું અને ઠંડું હોવું જોઈએ, નહીં તો ચોપ તેલમાં તૂટશે.'],'https://notoutofthebox.in/2023/05/echorer-chop-jackfruit-croquettes/');

add('posto-bora','Posto Bora','पोस्तो बोड़ा','પોસ્તો વડા','Bengali',35,[
 ['poppy seeds',180,'g','खसखस','ખસખસ'],['green chillies',12,'g','हरी मिर्च','લીલાં મરચાં'],['onion, finely chopped',60,'g','बारीक कटा प्याज','બારીક સમારેલી ડુંગળી'],['rice flour',35,'g','चावल का आटा','ચોખાનો લોટ'],['nigella seeds',3,'g','कलौंजी','કલૌંજી'],['salt',6,'g','नमक','મીઠું'],['water',85,'ml','पानी','પાણી'],['mustard oil',80,'ml','सरसों का तेल','સરસવનું તેલ']
],[
 ['Soak poppy seeds until softened, drain and grind with green chillies and a little measured water to a coarse thick paste.','खसखस नरम होने तक भिगोएँ, छानें और हरी मिर्च व थोड़े दिए पानी के साथ गाढ़ा दरदरा पीसें।','ખસખસ નરમ થાય ત્યાં સુધી પલાળો, નિતારી લીલાં મરચાં અને આપેલા થોડા પાણી સાથે ઘટ્ટ અધકચરી પેસ્ટ પીસો.'],
 ['Fold in onion, rice flour, nigella and salt. The mixture should hold its shape on a spoon; add only a few drops of remaining water if needed.','प्याज, चावल का आटा, कलौंजी और नमक मिलाएँ। मिश्रण चम्मच पर आकार थामे; ज़रूरत पर ही बचा पानी थोड़ा डालें।','ડુંગળી, ચોખાનો લોટ, કલૌંજી અને મીઠું ભેળવો. મિશ્રણ ચમચી પર આકાર જાળવે; જરૂર પડે તો જ બાકીનું પાણી થોડું ઉમેરો.'],
 ['Heat a thin layer of mustard oil until its raw aroma fades, then lower to medium heat.','तवे पर सरसों का थोड़ा तेल गरम कर कच्ची गंध दूर करें, फिर आँच मध्यम रखें।','તવા પર સરસવનું થોડું તેલ ગરમ કરી કાચી ગંધ દૂર કરો, પછી મધ્યમ તાપ રાખો.'],
 ['Drop small spoonfuls into the pan and flatten gently into little discs. Fry both sides until brown and firm, adding oil around the edges.','छोटे चम्मचभर मिश्रण डालकर हल्के चपटे गोले बनाएँ। किनारों पर तेल डालते हुए दोनों ओर भूरा और सख्त होने तक सेंकें।','નાની ચમચીભર મિશ્રણ નાખી હળવેથી ચપટી ગોળીઓ બનાવો. કિનારે તેલ ઉમેરતાં બંને બાજુ ભૂરું અને મજબૂત થાય ત્યાં સુધી શેકો.'],
 ['Drain briefly and serve hot beside rice and dal or as a tea-time snack.','थोड़ा तेल टपकाकर गरम बोड़े दाल-चावल के साथ या नाश्ते में परोसें।','થોડું તેલ નિતારી ગરમ વડા દાળ-ભાત સાથે અથવા નાસ્તામાં પીરસો.']
],['Do not grind the seeds completely smooth: a little texture makes the crisp crust characteristic.','खसखस को बिल्कुल चिकना न पीसें; हल्का दानापन इसकी कुरकुरी परत की पहचान है।','ખસખસ એકદમ લીસું ન પીસો; થોડો દાણાદારપણો તેની કરકરી પડની ઓળખ છે.'],'https://www.bongeats.com/recipe/postor-bora');

add('kurdai','Kurdai','कुरडई','કુરડઈ','Maharashtrian',2940,[
 ['whole wheat grains',500,'g','साबुत गेहूँ','આખા ઘઉં'],['water for soaking and batter',1800,'ml','भिगोने और घोल का पानी','પલાળવા અને ખીરા માટે પાણી'],['salt',10,'g','नमक','મીઠું'],['cumin seeds',6,'g','जीरा','જીરું'],['oil for greasing',15,'ml','चादर चिकनी करने का तेल','ચાદર ચોપડવા તેલ'],['oil for frying',600,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Wash wheat and soak overnight in part of the measured water. Drain, grind finely with fresh measured water and strain through muslin to collect the starch-rich milk.','गेहूँ धोकर दिए पानी के कुछ भाग में रात भर भिगोएँ। छानकर नए दिए पानी के साथ बारीक पीसें और मलमल से छानकर दूधिया रस लें।','ઘઉં ધોઈ આપેલા થોડા પાણીમાં રાતભર પલાળો. નિતારી નવા આપેલા પાણી સાથે બારીક પીસો અને મલમલથી ગાળી દૂધિયો રસ લો.'],
 ['Leave the wheat milk undisturbed so starch settles. Pour off the clear liquid carefully; repeat rinsing and settling until the starch is pale and clean.','गेहूँ का दूध बिना हिलाए रखें ताकि स्टार्च नीचे बैठे। ऊपर का साफ़ पानी सावधानी से हटाएँ; स्टार्च हल्का और साफ़ होने तक धोना और बैठाना दोहराएँ।','ઘઉંનું દૂધ હલાવ્યા વગર રાખો જેથી સ્ટાર્ચ નીચે બેસે. ઉપરનું સ્વચ્છ પાણી સાવધાનીથી કાઢો; સ્ટાર્ચ આછો અને સ્વચ્છ થાય ત્યાં સુધી ધોઈને બેસાડવાની પ્રક્રિયા દોહરાવો.'],
 ['Mix the settled starch with remaining water, salt and cumin. Cook over low heat, stirring constantly, until glossy, thick and translucent.','बैठा स्टार्च बचे पानी, नमक और जीरे से मिलाएँ। धीमी आँच पर लगातार चलाते हुए चमकदार, गाढ़ा और पारदर्शी पकाएँ।','બેસેલા સ્ટાર્ચમાં બાકીનું પાણી, મીઠું અને જીરું ભેળવો. ધીમા તાપે સતત હલાવતાં ચમકતું, ઘટ્ટ અને પારદર્શક થાય ત્યાં સુધી રાંધો.'],
 ['While warm, press the paste through a sev press into small coiled nests on a clean oiled sheet. Sun-dry completely for two days, turning once; keep covered from dust.','गरम रहते पेस्ट को सेव मशीन से तेल लगी साफ़ चादर पर छोटे घुमावदार चक्रों में निकालें। दो दिन पूरी तरह धूप में सुखाएँ और बीच में पलटें; धूल से बचाएँ।','ગરમ હોય ત્યારે પેસ્ટને સેવના સંચાથી તેલ લગાડેલી ચોખ્ખી ચાદર પર નાનાં ગૂંચવાયેલા ચક્રોમાં પાડો. બે દિવસ તડકામાં સંપૂર્ણ સુકવો અને વચ્ચે ફેરવો; ધૂળથી બચાવો.'],
 ['Store the brittle dried kurdai airtight. To serve, fry a few at a time in hot oil until they puff and turn crisp; drain immediately.','पूरी सूखी कुरडई बंद डिब्बे में रखें। परोसने के लिए गरम तेल में थोड़ी-थोड़ी डालें; फूलकर कुरकुरी होते ही निकालें।','સંપૂર્ણ સુકી કુરડઈ હવાચુસ્ત ડબ્બામાં રાખો. પીરસવા માટે ગરમ તેલમાં થોડીથોડી નાખો; ફૂલીને કરકરી થાય કે તરત કાઢો.']
],['Any residual moisture causes stored kurdai to spoil, so finish sun-drying before sealing.','थोड़ी भी नमी रखी कुरडई खराब कर सकती है, इसलिए डिब्बा बंद करने से पहले पूरी सुखाएँ।','જરાય ભેજ રહી જાય તો સાચવેલી કુરડઈ બગડે, એટલે ડબ્બો બંધ કરતાં પહેલાં પૂરી સુકવો.'],'https://www.youtube.com/watch?v=Qe1XnFWFmEM');

add('chana-dal-namkeen','Chana Dal Namkeen','चना दाल नमकीन','ચણા દાળનો નમકીન','North Indian',300,[
 ['split Bengal gram',400,'g','चना दाल','ચણા દાળ'],['water for soaking',1000,'ml','भिगोने का पानी','પલાળવાનું પાણી'],['salt',8,'g','नमक','મીઠું'],['red chilli powder',4,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['black salt',4,'g','काला नमक','સંચળ'],['dry mango powder',5,'g','अमचूर','આમચૂર'],['asafoetida',1,'g','हींग','હિંગ'],['oil for frying',700,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Rinse chana dal and soak until the grains swell but remain separate. Drain completely and spread on a clean towel until surface-dry.','चना दाल धोकर दाने फूलने लेकिन अलग रहने तक भिगोएँ। पूरा पानी निकालकर साफ़ कपड़े पर फैलाकर ऊपर से सुखाएँ।','ચણા દાળ ધોઈ દાણા ફૂલે પણ અલગ રહે ત્યાં સુધી પલાળો. સંપૂર્ણ નિતારી ચોખ્ખા કપડા પર પાથરી બહારથી સુકવો.'],
 ['Mix the powdered salt, chilli, black salt, mango powder and asafoetida in a dry bowl; keep ready beside the stove.','नमक, मिर्च, काला नमक, अमचूर और हींग एक सूखे कटोरे में मिलाकर चूल्हे के पास रखें।','મીઠું, મરચું, સંચળ, આમચૂર અને હિંગ સૂકા વાસણમાં ભેળવી ચૂલા પાસે રાખો.'],
 ['Heat oil over medium heat. Add a small batch of dry lentils carefully; fry while stirring until bubbling subsides and the dal is crisp throughout.','तेल मध्यम आँच पर गरम करें। सूखी दाल थोड़ी-थोड़ी सावधानी से डालें; बुलबुले कम हों और दाल अंदर तक कुरकुरी हो तब तक चलाते तलें।','તેલ મધ્યમ તાપે ગરમ કરો. સુકી દાળ થોડીથોડી સાવધાનીથી નાખો; પરપોટા ઘટે અને દાળ અંદર સુધી કરકરી થાય ત્યાં સુધી હલાવતાં તળો.'],
 ['Lift with a mesh skimmer, drain well and toss the warm dal immediately with spice mix. Repeat for remaining batches.','जालीदार झारे से निकालकर अच्छी तरह छानें और गरम दाल तुरंत मसाले में मिलाएँ। बाकी दाल भी ऐसे ही तलें।','જાળીદાર ઝારાથી કાઢી સારી રીતે નિતારો અને ગરમ દાળ તરત મસાલામાં ભેળવો. બાકી દાળ પણ આવી રીતે તળો.'],
 ['Cool fully before sealing in an airtight jar; serve in small bowls as a crunchy dry snack.','हवाबंद डिब्बे में रखने से पहले पूरी ठंडी करें; कुरकुरी सूखी नमकीन छोटी कटोरियों में परोसें।','હવાચુસ્ત ડબ્બામાં ભરતાં પહેલાં સંપૂર્ણ ઠંડી કરો; કરકરો સુકો નાસ્તો નાની વાટકીઓમાં પીરસો.']
],['Surface-dry lentils prevent dangerous splattering and give a crisp, separate-grain finish.','ऊपर से सूखी दाल तेल के छींटे रोकती है और हर दाना अलग कुरकुरा बनता है।','બહારથી સુકી દાળ તેલના છાંટા અટકાવે છે અને દરેક દાણો અલગ કરકરો બને છે.'],'https://hebbarskitchen.com/3-must-try-haldiram-namkeen-recipe/');

add('masala-kaju','Masala Kaju','मसाला काजू','મસાલા કાજુ','Indian',20,[
 ['whole cashews',400,'g','साबुत काजू','આખા કાજુ'],['ghee',25,'g','घी','ઘી'],['red chilli powder',5,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['chaat masala',8,'g','चाट मसाला','ચાટ મસાલો'],['turmeric powder',2,'g','हल्दी','હળદર'],['curry leaves',12,'g','करी पत्ते','મીઠા લીમડાનાં પાન'],['salt',4,'g','नमक','મીઠું']
],[
 ['Pat the cashews dry and separate any broken pieces so they roast evenly. Mix chilli, chaat masala, turmeric and salt in a small bowl.','काजू सुखाकर टूटे टुकड़े अलग करें ताकि बराबर भुनें। मिर्च, चाट मसाला, हल्दी और नमक छोटे कटोरे में मिलाएँ।','કાજુ સુકવી તૂટેલા ટુકડા અલગ કરો જેથી સરખા શેકાય. મરચું, ચાટ મસાલો, હળદર અને મીઠું નાની વાટકીમાં ભેળવો.'],
 ['Warm ghee in a heavy pan over low heat. Add curry leaves and cook until dry and crisp.','भारी पैन में धीमी आँच पर घी गरम करें। करी पत्ते डालकर सूखे और कुरकुरे होने तक पकाएँ।','ભારે કડાઈમાં ધીમા તાપે ઘી ગરમ કરો. મીઠા લીમડાનાં પાન નાખી સુકાં અને કરકરાં થાય ત્યાં સુધી રાંધો.'],
 ['Add cashews and stir constantly over low heat until golden on all sides; take care not to scorch the pointed tips.','काजू डालकर धीमी आँच पर लगातार चलाते हुए चारों ओर सुनहरे भूनें; नुकीले सिरे न जलें।','કાજુ નાખી ધીમા તાપે સતત હલાવતાં ચારે તરફ સોનેરી શેકો; અણીવાળા છેડા ન બળે.'],
 ['Turn off heat, immediately sprinkle the mixed spices over the warm nuts and toss until every cashew has a thin even coating.','आँच बंद कर गरम काजू पर मसाले तुरंत छिड़कें और सब पर पतली बराबर परत चढ़ने तक मिलाएँ।','તાપ બંધ કરી ગરમ કાજુ પર મસાલા તરત છાંટો અને બધાં પર પાતળું સરખું પડ ચડે ત્યાં સુધી ભેળવો.'],
 ['Spread in one layer to cool and crisp up, then serve or pack airtight.','एक परत में फैलाकर ठंडा और कुरकुरा करें, फिर परोसें या बंद डिब्बे में रखें।','એક પડમાં પાથરી ઠંડાં અને કરકરાં કરો, પછી પીરસો કે હવાચુસ્ત ડબ્બામાં ભરો.']
],['Spices added after the heat is switched off keep their colour and do not turn bitter.','आँच बंद करने के बाद मसाले डालने से रंग बना रहता है और स्वाद कड़वा नहीं होता।','તાપ બંધ કર્યા પછી મસાલા ઉમેરવાથી રંગ જળવાય છે અને સ્વાદ કડવો થતો નથી.'],'https://hebbarskitchen.com/roasted-cashew-nuts-recipe-roasted-kaju/');

add('paneer-manchurian','Paneer Manchurian','पनीर मंचूरियन','પનીર મંચુરિયન','Indo-Chinese',40,[
 ['paneer, cubes',450,'g','पनीर के टुकड़े','પનીરના ટુકડા'],['cornflour',70,'g','कॉर्नफ्लोर','કોર્નફ્લોર'],['all-purpose flour',45,'g','मैदा','મેંદો'],['red onion, diced',130,'g','लाल प्याज, चौकोर कटे','લાલ ડુંગળી, ચોરસ સમારેલી'],['green capsicum, diced',130,'g','हरी शिमला मिर्च, चौकोर कटी','લીલાં સિમલા મરચાં, ચોરસ સમારેલાં'],['garlic, chopped',18,'g','कटा लहसुन','સમારેલું લસણ'],['ginger, chopped',15,'g','कटा अदरक','સમારેલું આદુ'],['vegetarian soy sauce',25,'ml','शाकाहारी सोया सॉस','શાકાહારી સોયા સોસ'],['tomato ketchup',45,'g','टमाटर सॉस','ટામેટાંની સોસ'],['red chilli sauce',20,'ml','लाल मिर्च सॉस','લાલ મરચાંની સોસ'],['spring onion greens',25,'g','हरे प्याज के पत्ते','લીલી ડુંગળીના પાન'],['water',140,'ml','पानी','પાણી'],['salt',6,'g','नमक','મીઠું'],['oil',400,'ml','तेल','તેલ']
],[
 ['Pat paneer dry. Mix most cornflour with all-purpose flour, a pinch of salt and enough measured water to make a thin coating; reserve remaining cornflour for the sauce.','पनीर सुखाएँ। अधिकतर कॉर्नफ्लोर में मैदा, थोड़ा नमक और दिया पानी मिलाकर पतला लेप बनाएँ; बाकी कॉर्नफ्लोर सॉस के लिए रखें।','પનીર સુકવો. મોટા ભાગના કોર્નફ્લોરમાં મેંદો, થોડું મીઠું અને આપેલું પાણી ભેળવી પાતળું પડ બનાવો; બાકીનું કોર્નફ્લોર સોસ માટે રાખો.'],
 ['Coat paneer cubes lightly and shallow-fry in hot oil until golden at the edges. Drain without overcooking the soft centres.','पनीर पर हल्की परत लगाकर गरम तेल में किनारे सुनहरे होने तक तलें। नरम बीच को ज़्यादा पकाए बिना निकालें।','પનીરને હળવું ઢાંકી ગરમ તેલમાં કિનારીઓ સોનેરી થાય ત્યાં સુધી તળો. નરમ મધ્ય ભાગ વધુ રાંધ્યા વગર કાઢો.'],
 ['In a hot wok with a little oil, stir-fry garlic and ginger briefly, then add onion and capsicum; keep the vegetables slightly crisp.','गरम कड़ाही में थोड़े तेल में लहसुन और अदरक जल्दी भूनें, फिर प्याज और शिमला मिर्च डालें; सब्ज़ियाँ हल्की कुरकुरी रखें।','ગરમ કડાઈમાં થોડા તેલમાં લસણ અને આદુ ઝટપટ સાંતળો, પછી ડુંગળી અને સિમલા મરચાં નાખો; શાક થોડું કરકરું રાખો.'],
 ['Add soy sauce, ketchup and chilli sauce. Stir remaining cornflour with a splash of water, pour in and bubble until the glossy sauce just coats a spoon.','सोया सॉस, टमाटर सॉस और मिर्च सॉस डालें। बचा कॉर्नफ्लोर थोड़े पानी में घोलकर डालें और चमकदार सॉस चम्मच पर चढ़ने तक पकाएँ।','સોયા સોસ, ટામેટાંની સોસ અને મરચાંની સોસ ઉમેરો. બાકીનું કોર્નફ્લોર થોડા પાણીમાં ઓગાળી નાખો અને ચમકતી સોસ ચમચી પર ચડે ત્યાં સુધી ઉકાળો.'],
 ['Toss the fried paneer through the sauce only until coated. Finish with spring onion greens and serve immediately as a dry starter.','तला पनीर सॉस में बस लेप चढ़ने तक मिलाएँ। हरे प्याज के पत्ते डालकर सूखे स्टार्टर की तरह तुरंत परोसें।','તળેલું પનીર સોસમાં માત્ર પડ ચડે ત્યાં સુધી ભેળવો. લીલી ડુંગળીના પાન નાખી સુકા સ્ટાર્ટર તરીકે તરત પીરસો.']
],['Use a sauce with no animal-derived additives; the paneer should stay crisp-edged rather than sitting in gravy.','ऐसी सॉस लें जिसमें पशु-जन्य मिलावट न हो; पनीर ग्रेवी में डूबने के बजाय किनारों पर कुरकुरा रहे।','પ્રાણીજન્ય ઉમેરા વગરની સોસ લો; પનીર ગ્રેવીમાં ડૂબવાને બદલે કિનારીઓએ કરકરું રહે.'],'https://hebbarskitchen.com/paneer-manchurian-dry-recipe/');

add('methi-dhebra','Methi Dhebra','मेथी ढेबरा','મેથી ઢેબરા','Gujarati',40,[
 ['pearl millet flour',250,'g','बाजरे का आटा','બાજરીનો લોટ'],['whole wheat flour',100,'g','गेहूँ का आटा','ઘઉંનો લોટ'],['fresh fenugreek leaves, chopped',150,'g','कटी ताज़ा मेथी','સમારેલી તાજી મેથી'],['plain yogurt',120,'g','सादा दही','સાદું દહીં'],['sesame seeds',15,'g','तिल','તલ'],['ginger-green chilli paste',20,'g','अदरक-हरी मिर्च पेस्ट','આદુ-લીલા મરચાંની પેસ્ટ'],['turmeric powder',3,'g','हल्दी','હળદર'],['jaggery',15,'g','गुड़','ગોળ'],['salt',8,'g','नमक','મીઠું'],['water',60,'ml','पानी','પાણી'],['oil for cooking',60,'ml','सेंकने का तेल','શેકવા માટે તેલ']
],[
 ['Wash fenugreek, dry it and chop finely; discard coarse stems. Dissolve jaggery in yogurt.','मेथी धोकर सुखाएँ और बारीक काटें; मोटे डंठल हटाएँ। गुड़ दही में घोलें।','મેથી ધોઈ સુકવી બારીક સમારો; જાડી દાંડીઓ કાઢો. ગોળ દહીંમાં ઓગાળો.'],
 ['Combine both flours, fenugreek, sesame, chilli-ginger paste, turmeric and salt. Add sweetened yogurt and just enough water to make a firm pliable dough.','दोनों आटे, मेथी, तिल, मिर्च-अदरक पेस्ट, हल्दी और नमक मिलाएँ। गुड़ वाला दही और बस ज़रूरी पानी डालकर सख्त लचीला आटा गूँधें।','બંને લોટ, મેથી, તલ, મરચાં-આદુની પેસ્ટ, હળદર અને મીઠું ભેળવો. ગોળવાળું દહીં અને જરૂર પૂરતું પાણી ઉમેરી કઠણ પણ વળી શકે એવો લોટ બાંધો.'],
 ['Rest the dough covered briefly. Divide into small balls and roll each between sheets into a moderately thick round.','आटा कुछ देर ढककर रखें। छोटे गोले बनाकर चादरों के बीच मध्यम मोटाई के गोल बेलें।','લોટ થોડી વાર ઢાંકીને રાખો. નાના લુવા બનાવી ચાદરો વચ્ચે મધ્યમ જાડાઈના ગોળ વણો.'],
 ['Cook on a medium-hot tawa, turning and brushing lightly with oil until both sides have brown spots and the middle is cooked.','मध्यम गरम तवे पर पलटते और हल्का तेल लगाते हुए दोनों तरफ भूरे धब्बे और बीच तक पकने तक सेंकें।','મધ્યમ ગરમ તવા પર ફેરવતાં અને થોડું તેલ લગાવતાં બંને બાજુ ભૂરા ટપકા પડે અને મધ્ય સુધી શેકાય ત્યાં સુધી શેકો.'],
 ['Stack under a cloth to stay soft. Serve warm with yogurt, pickle or a little butter.','नरम रखने के लिए कपड़े में ढककर रखें। दही, अचार या थोड़ा मक्खन साथ गरम परोसें।','નરમ રહે માટે કપડાથી ઢાંકી રાખો. દહીં, અથાણું કે થોડું માખણ સાથે ગરમ પીરસો.']
],['Roll between sheets because millet flour cracks easily; thick dhebra stay soft rather than drying out.','बाजरे का आटा जल्दी फटता है इसलिए चादरों के बीच बेलें; थोड़ा मोटा ढेबरा नरम रहता है।','બાજરીનો લોટ સહેલાઈથી તૂટે છે એટલે ચાદરો વચ્ચે વણો; થોડું જાડું ઢેબરું નરમ રહે છે.'],'https://hebbarskitchen.com/gujarati-methi-na-dhebra-recipe/');

add('beguni','Beguni','बेगुनी','બેગુની','Bengali',35,[
 ['long eggplant',350,'g','लंबा बैंगन','લાંબું રીંગણ'],['gram flour',130,'g','बेसन','ચણાનો લોટ'],['rice flour',35,'g','चावल का आटा','ચોખાનો લોટ'],['turmeric powder',3,'g','हल्दी','હળદર'],['red chilli powder',4,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['sugar',5,'g','चीनी','ખાંડ'],['salt',8,'g','नमक','મીઠું'],['water',165,'ml','पानी','પાણી'],['mustard oil for frying',600,'ml','तलने का सरसों तेल','તળવા માટે સરસવનું તેલ'],['black salt',3,'g','काला नमक','સંચળ']
],[
 ['Slice eggplant lengthwise into thin even sheets. Sprinkle with part of the salt and sugar, leave briefly, then pat very dry.','बैंगन लंबे पतले बराबर टुकड़ों में काटें। थोड़ा नमक और चीनी छिड़ककर कुछ देर रखें, फिर अच्छी तरह सुखाएँ।','રીંગણને લંબાઈમાં પાતળા સરખા કટકા કરો. થોડું મીઠું અને ખાંડ છાંટી થોડી વાર રાખો, પછી બરાબર સુકવો.'],
 ['Whisk gram flour, rice flour, turmeric, chilli and remaining salt with water into a smooth batter that coats the back of a spoon.','बेसन, चावल का आटा, हल्दी, मिर्च और बचा नमक पानी के साथ फेंटकर चम्मच के पीछे टिकने वाला चिकना घोल बनाएँ।','ચણાનો લોટ, ચોખાનો લોટ, હળદર, મરચું અને બાકીનું મીઠું પાણી સાથે ફેંટી ચમચીની પાછળ ચોંટે એવું લીસું ખીરું બનાવો.'],
 ['Heat mustard oil until its raw aroma fades, then keep it moderately hot. Dip each dry slice and shake off excess batter.','सरसों तेल की कच्ची गंध दूर होने तक गरम करें, फिर मध्यम गरम रखें। हर सूखा टुकड़ा घोल में डुबोकर अतिरिक्त घोल झाड़ें।','સરસવના તેલની કાચી ગંધ દૂર થાય ત્યાં સુધી ગરમ કરો, પછી મધ્યમ ગરમ રાખો. દરેક સૂકા કટકાને ખીરામાં ડુબાડી વધારાનું ખીરું ઝાડો.'],
 ['Fry a few slices at a time, turning once, until the coating is crisp and the eggplant tender. Drain on a rack.','थोड़े-थोड़े टुकड़े एक बार पलटकर परत कुरकुरी और बैंगन नरम होने तक तलें। जाली पर निकालें।','થોડા થોડા કટકા એક વાર ફેરવી પડ કરકરું અને રીંગણ નરમ થાય ત્યાં સુધી તળો. જાળી પર કાઢો.'],
 ['Dust with black salt and serve immediately alongside tea or khichuri.','काला नमक छिड़ककर चाय या खिचुड़ी के साथ तुरंत परोसें।','સંચળ છાંટી ચા કે ખીચડી સાથે તરત પીરસો.']
],['Drying the slices before coating is the key to a thin crisp beguni rather than a soggy one.','घोल लगाने से पहले टुकड़े सुखाना पतली कुरकुरी बेगुनी के लिए ज़रूरी है।','ખીરું લગાડતાં પહેલાં કટકા સુકવવા પાતળી કરકરી બેગુની માટે જરૂરી છે.'],'https://www.bongeats.com/recipe/beguni');

add('aloo-chop','Aloo Chop','आलू चॉप','બટાકા ચોપ','Bengali',50,[
 ['potatoes',600,'g','आलू','બટાકા'],['gram flour',160,'g','बेसन','ચણાનો લોટ'],['rice flour',35,'g','चावल का आटा','ચોખાનો લોટ'],['ginger, grated',18,'g','कसा अदरक','છીણેલું આદુ'],['green chillies',12,'g','हरी मिर्च','લીલાં મરચાં'],['roasted cumin powder',5,'g','भुना जीरा','શેકેલું જીરું'],['turmeric powder',3,'g','हल्दी','હળદર'],['salt',9,'g','नमक','મીઠું'],['water',190,'ml','पानी','પાણી'],['mustard oil for frying',650,'ml','तलने का सरसों तेल','તળવા માટે સરસવનું તેલ']
],[
 ['Boil potatoes until just tender, drain thoroughly and mash while warm; let steam escape so the filling becomes dry.','आलू बस नरम होने तक उबालें, पूरा पानी निकालकर गरम ही मसलें; भाप निकलने दें ताकि भरावन सूखा हो।','બટાકા માત્ર નરમ થાય ત્યાં સુધી બાફો, સંપૂર્ણ નિતારી ગરમ હોય ત્યારે મસળો; વરાળ નીકળવા દો જેથી પૂરણ સુકું થાય.'],
 ['Mix potato with ginger, chopped chillies, cumin, a little turmeric and salt. Shape into small flattened discs and chill until firm.','आलू में अदरक, कटी मिर्च, जीरा, थोड़ी हल्दी और नमक मिलाएँ। छोटे चपटे गोले बनाकर सख्त होने तक ठंडा करें।','બટાકામાં આદુ, સમારેલાં મરચાં, જીરું, થોડી હળદર અને મીઠું ભેળવો. નાની ચપટી ગોળીઓ બનાવી મજબૂત થાય ત્યાં સુધી ઠંડી કરો.'],
 ['Whisk gram flour, rice flour, remaining turmeric and water into a smooth medium-thick batter.','बेसन, चावल का आटा, बची हल्दी और पानी से मध्यम गाढ़ा चिकना घोल फेंटें।','ચણાનો લોટ, ચોખાનો લોટ, બાકી હળદર અને પાણીથી મધ્યમ ઘટ્ટ લીસું ખીરું ફેંટો.'],
 ['Heat mustard oil until the raw smell fades. Dip each potato disc to coat fully and fry in batches, turning until golden and crisp.','सरसों तेल की कच्ची गंध दूर करें। हर आलू चॉप घोल में पूरी तरह लपेटकर थोड़े-थोड़े तलें और सुनहरे कुरकुरे होने तक पलटें।','સરસવના તેલની કાચી ગંધ દૂર કરો. દરેક બટાકા ચોપ ખીરામાં સંપૂર્ણ ઢાંકી થોડા થોડા તળો અને સોનેરી કરકરા થાય ત્યાં સુધી ફેરવો.'],
 ['Drain well and serve hot with kasundi mustard and puffed rice if desired.','अच्छी तरह तेल छानकर कसुंदी सरसों और चाहें तो मुरमुरे के साथ गरम परोसें।','સારી રીતે તેલ નિતારી કાસુંદી સરસવ અને ઇચ્છો તો મમરા સાથે ગરમ પીરસો.']
],['Keep the potato patties flat, not round like a bonda; that is the familiar Bengali telebhaja shape.','आलू के चॉप गोल बोंडा जैसे नहीं, चपटे रखें; यही बंगाली तले नाश्ते की पहचान है।','બટાકાના ચોપ ગોળ બોંડા જેવા નહીં, ચપટા રાખો; આ બંગાળી તળેલા નાસ્તાની ઓળખ છે.'],'https://www.yummefy.com/aloo-chop-recipe.html');

add('phuluri','Phuluri','फुलुरी','ફુલુરી','Bengali',25,[
 ['gram flour',220,'g','बेसन','ચણાનો લોટ'],['rice flour',25,'g','चावल का आटा','ચોખાનો લોટ'],['green chillies, minced',12,'g','बारीक हरी मिर्च','બારીક લીલાં મરચાં'],['nigella seeds',4,'g','कलौंजी','કલૌંજી'],['turmeric powder',2,'g','हल्दी','હળદર'],['salt',7,'g','नमक','મીઠું'],['water',240,'ml','पानी','પાણી'],['oil for frying',600,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Sift gram flour and rice flour into a bowl with turmeric and salt; stir in nigella and finely minced chilli.','बेसन और चावल का आटा हल्दी और नमक के साथ छानें; कलौंजी और बारीक मिर्च मिलाएँ।','ચણાનો અને ચોખાનો લોટ હળદર અને મીઠા સાથે ચાળો; કલૌંજી અને બારીક મરચાં ભેળવો.'],
 ['Add water gradually and beat vigorously until the batter is smooth, airy and thick enough to mound on a spoon.','धीरे-धीरे पानी डालकर तेज़ फेंटें जब तक घोल चिकना, हवादार और चम्मच पर ढेर-सा टिकने वाला हो।','ધીમે ધીમે પાણી ઉમેરી જોરથી ફેંટો જ્યાં સુધી ખીરું લીસું, હવાદાર અને ચમચી પર ઢગલો થાય એવું ઘટ્ટ બને.'],
 ['Rest the batter briefly while heating oil over medium heat. Beat it once more just before frying.','तेल मध्यम आँच पर गरम करते समय घोल कुछ देर रखें। तलने से ठीक पहले फिर फेंटें।','તેલ મધ્યમ તાપે ગરમ થાય ત્યાં સુધી ખીરું થોડી વાર રાખો. તળતાં પહેલાં ફરી ફેંટો.'],
 ['Drop small rounded spoonfuls into oil without overcrowding. Turn until puffed, cooked through and golden all around.','छोटे गोल चम्मचभर घोल तेल में डालें, भीड़ न करें। फूले, अंदर तक पके और चारों ओर सुनहरे हों तब तक पलटें।','નાની ગોળ ચમચીભર ખીરું તેલમાં નાખો, ભીડ ન કરો. ફૂલે, અંદર સુધી રંધાય અને ચારે બાજુ સોનેરી થાય ત્યાં સુધી ફેરવો.'],
 ['Drain on a rack and serve hot with kasundi or a tangy chutney.','जाली पर निकालकर कसुंदी या खट्टी चटनी के साथ गरम परोसें।','જાળી પર કાઢી કાસુંદી કે ખાટી ચટણી સાથે ગરમ પીરસો.']
],['Beating the batter adds air; dense batter produces heavy fritters instead of light phuluri.','घोल फेंटने से हवा भरती है; बिना फेंटा घोल हल्की फुलुरी के बजाय भारी पकोड़े बनाता है।','ખીરું ફેંટવાથી હવા ભળે છે; ન ફેંટેલું ખીરું હલકી ફુલુરીને બદલે ભારે પકોડા બનાવે છે.'],'https://www.bongcookbook.com/2015/04/fuluri-phuluri-Bengali-fried-snack.html');

add('piaji','Piaji','पियाजी','પિયાજી','Odia',300,[
 ['split Bengal gram',250,'g','चना दाल','ચણા દાળ'],['red onions, thinly sliced',350,'g','लाल प्याज, पतले कटे','લાલ ડુંગળી, પાતળી સમારેલી'],['green chillies',15,'g','हरी मिर्च','લીલાં મરચાં'],['ginger',18,'g','अदरक','આદુ'],['coriander leaves',20,'g','हरा धनिया','લીલી કોથમીર'],['cumin seeds',5,'g','जीरा','જીરું'],['salt',9,'g','नमक','મીઠું'],['water for soaking',650,'ml','भिगोने का पानी','પલાળવાનું પાણી'],['oil for frying',650,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Wash and soak chana dal until plump. Drain completely; keep a small handful whole and grind the rest coarsely without extra water.','चना दाल धोकर फूलने तक भिगोएँ। पूरा पानी निकालें; थोड़ी दाल साबुत रखें और बाकी बिना पानी दरदरी पीसें।','ચણા દાળ ધોઈ ફૂલે ત્યાં સુધી પલાળો. સંપૂર્ણ નિતારો; થોડી દાળ આખી રાખો અને બાકીની પાણી વગર અધકચરી પીસો.'],
 ['Mix the dal paste with whole dal, onion, minced chillies, ginger, coriander, cumin and salt. Squeeze gently so the onion moisture binds the mixture.','दाल पेस्ट में साबुत दाल, प्याज, बारीक मिर्च, अदरक, धनिया, जीरा और नमक मिलाएँ। हल्का दबाएँ ताकि प्याज की नमी मिश्रण बाँधे।','દાળની પેસ્ટમાં આખી દાળ, ડુંગળી, બારીક મરચાં, આદુ, કોથમીર, જીરું અને મીઠું ભેળવો. હળવે દબાવો જેથી ડુંગળીનો રસ મિશ્રણ બાંધે.'],
 ['Heat oil over medium heat. Press portions between damp palms into small flat patties with ragged edges.','तेल मध्यम आँच पर गरम करें। गीली हथेलियों के बीच छोटे हिस्से दबाकर खुरदरे किनारे वाले चपटे वड़े बनाएँ।','તેલ મધ્યમ તાપે ગરમ કરો. ભીના હાથ વચ્ચે નાના ભાગને ચપટા, ખરબચડી કિનારીવાળા વડા બનાવો.'],
 ['Slide patties into oil in small batches. Fry slowly, turning, until both sides are deep golden and the lentil centre is fully cooked.','वड़े थोड़े-थोड़े तेल में डालें। पलटते हुए धीरे तलें जब तक दोनों तरफ गहरा सुनहरा और बीच की दाल पूरी पकी न हो।','વડા થોડા થોડા તેલમાં નાખો. ફેરવતાં ધીમે તળો જ્યાં સુધી બંને બાજુ ઘેરા સોનેરી અને મધ્યની દાળ પૂરી રંધાય નહીં.'],
 ['Drain well and serve while crisp, traditionally with puffed rice and tea.','अच्छी तरह तेल छानें और कुरकुरे रहते परोसें; पारंपरिक रूप से मुरमुरे और चाय के साथ।','સારી રીતે તેલ નિતારો અને કરકરા હોય ત્યારે પીરસો; પરંપરાગત રીતે મમરા અને ચા સાથે.']
],['Coarse dal and flattened shape distinguish piaji from soft round lentil fritters.','दरदरी दाल और चपटा आकार पियाजी को नरम गोल दाल-पकोड़ों से अलग करते हैं।','અધકચરી દાળ અને ચપટો આકાર પિયાજીને નરમ ગોળ દાળ-પકોડાથી અલગ પાડે છે.'],'https://www.firsttimercook.com/piaji-chana-dal-fritters-in-odia-style/');

add('pazham-pori','Pazham Pori','पज़म पोरी','પઝમ પોરી','Kerala',30,[
 ['ripe plantains',600,'g','पके केले','પાકાં કેળાં'],['all-purpose flour',160,'g','मैदा','મેંદો'],['rice flour',35,'g','चावल का आटा','ચોખાનો લોટ'],['sugar',25,'g','चीनी','ખાંડ'],['turmeric powder',1,'g','हल्दी','હળદર'],['ground cardamom',2,'g','पिसी इलायची','ઈલાયચી પાઉડર'],['salt',2,'g','नमक','મીઠું'],['water',205,'ml','पानी','પાણી'],['coconut oil for frying',600,'ml','तलने का नारियल तेल','તળવા માટે નાળિયેરનું તેલ']
],[
 ['Peel ripe but firm plantains and cut lengthwise into long even slices; avoid slices so thin that they break.','पके मगर सख्त केले छीलकर लंबाई में लंबे बराबर टुकड़े काटें; इतने पतले न काटें कि टूटें।','પાકાં પણ મજબૂત કેળાં છોલીને લંબાઈમાં લાંબા સરખા કટકા કરો; તૂટી જાય એટલા પાતળા ન કરો.'],
 ['Whisk flour, rice flour, sugar, turmeric, cardamom and salt. Gradually add water for a smooth batter that clings in a thin layer.','मैदा, चावल का आटा, चीनी, हल्दी, इलायची और नमक फेंटें। धीरे पानी मिलाकर पतली परत में चिपकने वाला चिकना घोल बनाएँ।','મેંદો, ચોખાનો લોટ, ખાંડ, હળદર, ઈલાયચી અને મીઠું ફેંટો. ધીમે પાણી ઉમેરી પાતળું પડ ચોંટે એવું લીસું ખીરું બનાવો.'],
 ['Heat coconut oil over medium heat. Dip each plantain slice, let excess batter drip away and lower gently into the oil.','नारियल तेल मध्यम आँच पर गरम करें। हर केले के टुकड़े को घोल में डुबोएँ, अतिरिक्त टपकाएँ और धीरे तेल में डालें।','નાળિયેરનું તેલ મધ્યમ તાપે ગરમ કરો. દરેક કેળાના કટકાને ખીરામાં ડુબાડી વધારું ટપકવા દો અને હળવે તેલમાં નાખો.'],
 ['Fry in small batches, turning until each fritter is golden outside and the fruit within is soft and sweet.','थोड़े-थोड़े तलें, पलटते हुए बाहर सुनहरा और अंदर फल नरम मीठा होने तक पकाएँ।','થોડા થોડા તળો, ફેરવતાં બહાર સોનેરી અને અંદર ફળ નરમ મીઠું થાય ત્યાં સુધી રાંધો.'],
 ['Drain on a rack and serve warm with Kerala tea.','जाली पर निकालकर केरल की चाय के साथ गरम परोसें।','જાળી પર કાઢી કેરળની ચા સાથે ગરમ પીરસો.']
],['Use ripe plantain rather than raw cooking banana; ripeness gives the signature sweet soft centre.','कच्चे कुकिंग केले के बजाय पके केले लें; पकापन इसका मीठा नरम बीच देता है।','કાચા રસોઈના કેળાને બદલે પાકાં કેળાં લો; પાકેલું કેળું તેનો મીઠો નરમ મધ્ય ભાગ આપે છે.'],'https://www.vegrecipesofindia.com/pazham-pori-recipe-ethakka-appam/');

add('parippu-vada','Parippu Vada','परिप्पु वड़ा','પરિપ્પુ વડા','Kerala',300,[
 ['split Bengal gram',350,'g','चना दाल','ચણા દાળ'],['shallots, chopped',100,'g','कटे छोटे प्याज','સમારેલી નાની ડુંગળી'],['dried red chillies',10,'g','सूखी लाल मिर्च','સૂકાં લાલ મરચાં'],['ginger',18,'g','अदरक','આદુ'],['curry leaves',15,'g','करी पत्ते','મીઠા લીમડાનાં પાન'],['fennel seeds',6,'g','सौंफ','વરિયાળી'],['salt',8,'g','नमक','મીઠું'],['water for soaking',900,'ml','भिगोने का पानी','પલાળવાનું પાણી'],['coconut oil for frying',650,'ml','तलने का नारियल तेल','તળવા માટે નાળિયેરનું તેલ']
],[
 ['Rinse and soak chana dal until swollen. Drain extremely well; reserve a small handful of whole soaked dal.','चना दाल धोकर फूलने तक भिगोएँ। बहुत अच्छी तरह छानें; थोड़ी साबुत भीगी दाल अलग रखें।','ચણા દાળ ધોઈ ફૂલે ત્યાં સુધી પલાળો. ખૂબ સારી રીતે નિતારો; થોડી આખી પલાળેલી દાળ અલગ રાખો.'],
 ['Pulse the rest coarsely with dried chilli, ginger and fennel; stop before it becomes a smooth paste.','बाकी दाल को सूखी मिर्च, अदरक और सौंफ के साथ दरदरा पीसें; चिकना पेस्ट बनने से पहले रोकें।','બાકીની દાળને સૂકાં મરચાં, આદુ અને વરિયાળી સાથે અધકચરી વાટો; લીસી પેસ્ટ થાય તે પહેલાં રોકો.'],
 ['Fold in whole dal, shallots, finely chopped curry leaves and salt. Press small portions into fairly thin discs.','साबुत दाल, छोटे प्याज, बारीक करी पत्ते और नमक मिलाएँ। छोटे हिस्से दबाकर थोड़े पतले गोले बनाएँ।','આખી દાળ, નાની ડુંગળી, બારીક મીઠા લીમડાનાં પાન અને મીઠું ભેળવો. નાના ભાગ દબાવી થોડા પાતળા ગોળ બનાવો.'],
 ['Heat coconut oil over medium heat. Fry a few patties at a time, turning until deep gold and crisp all the way through.','नारियल तेल मध्यम आँच पर गरम करें। थोड़े वड़े एक बार में तलें, पलटते हुए अंदर तक गहरे सुनहरे और कुरकुरे करें।','નાળિયેરનું તેલ મધ્યમ તાપે ગરમ કરો. થોડા વડા એક સમયે તળો, ફેરવતાં અંદર સુધી ઘેરા સોનેરી અને કરકરા કરો.'],
 ['Drain on a rack and serve immediately with coconut chutney and tea.','जाली पर निकालकर नारियल चटनी और चाय के साथ तुरंत परोसें।','જાળી પર કાઢી નાળિયેરની ચટણી અને ચા સાથે તરત પીરસો.']
],['Coarse dal and a flat patty give parippu vada its crunchy texture; a wet smooth paste will not.','दरदरी दाल और चपटा आकार वड़े को कुरकुरा बनाते हैं; गीला चिकना पेस्ट ऐसा नहीं करेगा।','અધકચરી દાળ અને ચપટો આકાર વડાને કરકરા બનાવે છે; ભીની લીસી પેસ્ટ એવું નહીં કરે.'],'https://www.vegrecipesofindia.com/masala-vada-recipe-masala-vadai/');

add('mysore-bonda','Mysore Bonda','मैसूर बोंडा','મૈસૂર બોંડા','Karnataka',45,[
 ['all-purpose flour',280,'g','मैदा','મેંદો'],['plain yogurt',220,'g','सादा दही','સાદું દહીં'],['rice flour',45,'g','चावल का आटा','ચોખાનો લોટ'],['fresh coconut, finely chopped',60,'g','बारीक ताज़ा नारियल','બારીક તાજું નાળિયેર'],['green chillies, chopped',12,'g','कटी हरी मिर्च','સમારેલાં લીલાં મરચાં'],['ginger, minced',15,'g','बारीक अदरक','બારીક આદુ'],['cumin seeds',5,'g','जीरा','જીરું'],['baking soda',2,'g','खाने का सोडा','ખાવાનો સોડા'],['salt',8,'g','नमक','મીઠું'],['water',80,'ml','पानी','પાણી'],['oil for frying',650,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Whisk yogurt smooth. Stir in both flours, coconut, chilli, ginger, cumin and salt to make a thick batter.','दही चिकना फेंटें। दोनों आटे, नारियल, मिर्च, अदरक, जीरा और नमक डालकर गाढ़ा घोल बनाएँ।','દહીં લીસું ફેંટો. બંને લોટ, નાળિયેર, મરચાં, આદુ, જીરું અને મીઠું ઉમેરી ઘટ્ટ ખીરું બનાવો.'],
 ['Add just enough water to let the batter fall slowly from a spoon. Beat well to incorporate air; rest briefly.','बस इतना पानी डालें कि घोल चम्मच से धीरे गिरे। हवा भरने के लिए अच्छी तरह फेंटें; थोड़ी देर रखें।','ખીરું ચમચીમાંથી ધીમે પડે એટલું જ પાણી ઉમેરો. હવા ભળે માટે સારી રીતે ફેંટો; થોડી વાર રાખો.'],
 ['Fold in baking soda just before frying. Heat oil to medium; a small drop of batter should rise steadily, not darken at once.','तलने से ठीक पहले खाने का सोडा मिलाएँ। तेल मध्यम गरम करें; घोल की छोटी बूँद धीरे ऊपर आए, तुरंत काली न हो।','તળતાં પહેલાં ખાવાનો સોડા ભેળવો. તેલ મધ્યમ ગરમ કરો; ખીરાનું નાનું ટીપું ધીમે ઉપર આવે, તરત કાળું ન થાય.'],
 ['Drop rounded spoonfuls into oil, leaving space for them to puff. Turn gently and fry until evenly golden and cooked in the centre.','गोल चम्मचभर घोल तेल में डालें और फूलने की जगह छोड़ें। हल्के पलटकर बराबर सुनहरे और बीच तक पके तलें।','ગોળ ચમચીભર ખીરું તેલમાં નાખો અને ફૂલવાની જગ્યા છોડો. હળવે ફેરવી સરખા સોનેરી અને મધ્ય સુધી રંધાય ત્યાં સુધી તળો.'],
 ['Drain and serve hot with coconut chutney; the inside should be light and spongy.','तेल छानकर नारियल चटनी के साथ गरम परोसें; भीतर हल्का और स्पंजी होना चाहिए।','તેલ નિતારી નાળિયેરની ચટણી સાથે ગરમ પીરસો; અંદર હળવું અને પોચું હોવું જોઈએ.']
],['This instant bonda uses soda for lift; unlike goli baje, the batter does not need long fermentation.','यह तुरंत बनने वाला बोंडा फूलने के लिए सोडा लेता है; गोली बाजे की तरह लंबे खमीर की ज़रूरत नहीं।','આ તરત બનતું બોંડા ફૂલવા સોડા વાપરે છે; ગોલી બાજેની જેમ લાંબા આથાની જરૂર નથી.'],'https://hebbarskitchen.com/mysore-bonda-recipe-mysore-bajji/');

add('goli-baje','Goli Baje','गोली बाजे','ગોલી બાજે','Karnataka',210,[
 ['all-purpose flour',250,'g','मैदा','મેંદો'],['plain yogurt',220,'g','सादा दही','સાદું દહીં'],['rice flour',55,'g','चावल का आटा','ચોખાનો લોટ'],['fresh coconut bits',65,'g','ताज़ा नारियल के टुकड़े','તાજા નાળિયેરના ટુકડા'],['green chillies, chopped',12,'g','कटी हरी मिर्च','સમારેલાં લીલાં મરચાં'],['ginger, minced',16,'g','बारीक अदरक','બારીક આદુ'],['curry leaves, chopped',12,'g','कटे करी पत्ते','સમારેલાં મીઠા લીમડાનાં પાન'],['salt',8,'g','नमक','મીઠું'],['water',70,'ml','पानी','પાણી'],['oil for frying',700,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Whisk yogurt with a little measured water. Mix in both flours and salt, beating into a thick smooth batter.','दही में थोड़ा दिया पानी फेंटें। दोनों आटे और नमक मिलाकर गाढ़ा चिकना घोल बनाएँ।','દહીંમાં આપેલું થોડું પાણી ફેંટો. બંને લોટ અને મીઠું ભેળવી ઘટ્ટ લીસું ખીરું બનાવો.'],
 ['Cover and rest the batter in a warm spot until lightly tangy and bubbly; this coastal version relies on this rest for its soft interior.','घोल ढककर गरम जगह हल्का खट्टा और बुलबुला बनने तक रखें; समुद्री तट वाला रूप इस विश्राम से भीतर नरम बनता है।','ખીરું ઢાંકી ગરમ જગ્યાએ થોડું ખાટું અને પરપોટાવાળું થાય ત્યાં સુધી રાખો; દરિયાકાંઠાના આ પ્રકારમાં આથાથી અંદર નરમ બને છે.'],
 ['Fold in coconut, chilli, ginger and curry leaves without knocking all the air out. Add only enough remaining water if the batter is too stiff.','नारियल, मिर्च, अदरक और करी पत्ते हल्के हाथ से मिलाएँ ताकि हवा बनी रहे। घोल बहुत सख्त हो तभी बचा पानी डालें।','નાળિયેર, મરચાં, આદુ અને મીઠા લીમડાનાં પાન હળવે ભેળવો જેથી હવા જળવાય. ખીરું બહુ કઠણ હોય ત્યારે જ બાકીનું પાણી ઉમેરો.'],
 ['Heat oil over medium heat. Drop small rounded portions and fry slowly, turning as they puff into irregular golden balls.','तेल मध्यम आँच पर गरम करें। छोटे गोल हिस्से डालकर धीरे तलें; फूलकर अनगढ़ सुनहरी गोलियाँ बनें तब तक पलटें।','તેલ મધ્યમ તાપે ગરમ કરો. નાનાં ગોળ ભાગ નાખી ધીમે તળો; ફૂલીને ખરબચડી સોનેરી ગોળીઓ બને ત્યાં સુધી ફેરવો.'],
 ['Drain and serve fresh with coconut chutney; the crust is lightly crisp and the middle fluffy.','तेल छानकर नारियल चटनी के साथ ताज़ा परोसें; बाहर हल्का कुरकुरा और भीतर फूला नरम हो।','તેલ નિતારી નાળિયેરની ચટણી સાથે તાજું પીરસો; બહાર હળવું કરકરું અને અંદર ફૂલેલું નરમ હોય.']
],['A thick, rested batter gives goli baje its characteristic tang and airy texture.','गाढ़ा विश्राम किया घोल गोली बाजे को खास खट्टापन और हल्की बनावट देता है।','ઘટ્ટ આથેલું ખીરું ગોલી બાજેને ખાસ ખટાશ અને હલકી બનાવટ આપે છે.'],'https://karnatakatourism.org/en/experiences/goli-baje/');

add('maddur-vada','Maddur Vada','मद्दूर वड़ा','મદ્દુર વડા','Karnataka',35,[
 ['fine semolina',180,'g','बारीक सूजी','બારીક રવો'],['rice flour',120,'g','चावल का आटा','ચોખાનો લોટ'],['all-purpose flour',65,'g','मैदा','મેંદો'],['red onions, thinly sliced',250,'g','लाल प्याज, पतले कटे','લાલ ડુંગળી, પાતળી સમારેલી'],['green chillies',15,'g','हरी मिर्च','લીલાં મરચાં'],['curry leaves',15,'g','करी पत्ते','મીઠા લીમડાનાં પાન'],['cumin seeds',5,'g','जीरा','જીરું'],['salt',9,'g','नमक','મીઠું'],['water',120,'ml','पानी','પાણી'],['oil for frying',650,'ml','तलने का तेल','તળવા માટે તેલ']
],[
 ['Mix semolina, rice flour, all-purpose flour, onion, minced chilli, curry leaves, cumin and salt. Rub together to draw moisture from onion.','सूजी, चावल का आटा, मैदा, प्याज, बारीक मिर्च, करी पत्ते, जीरा और नमक मिलाएँ। प्याज की नमी निकलने तक हाथ से मलें।','રવો, ચોખાનો લોટ, મેંદો, ડુંગળી, બારીક મરચાં, મીઠા લીમડાનાં પાન, જીરું અને મીઠું ભેળવો. ડુંગળીનો રસ નીકળે ત્યાં સુધી હાથથી ચોળો.'],
 ['Add water gradually and bring together into a stiff, rough dough; do not knead it smooth like roti dough.','पानी धीरे-धीरे डालकर सख्त खुरदरा आटा जोड़ें; रोटी के आटे जैसा चिकना न गूँधें।','પાણી ધીમે ધીમે ઉમેરી કઠણ ખરબચડો લોટ ભેગો કરો; રોટલીના લોટ જેવો લીસો ન મસળો.'],
 ['Divide into small balls and flatten thinly between oiled sheets, leaving ragged onion-studded edges.','छोटे गोले तेल लगी चादरों के बीच पतले दबाएँ, प्याज वाले खुरदरे किनारे रहने दें।','નાના લુવા તેલ લગાડેલી ચાદરો વચ્ચે પાતળા દબાવો, ડુંગળીવાળી ખરબચડી કિનારીઓ રહેવા દો.'],
 ['Fry in moderately hot oil, turning until both sides are richly golden and the centre has no raw flour taste.','मध्यम गरम तेल में पलटकर दोनों ओर गहरे सुनहरे और बीच का कच्चा आटा पकने तक तलें।','મધ્યમ ગરમ તેલમાં ફેરવી બંને બાજુ ઘેરા સોનેરી અને મધ્યનો કાચો લોટ રંધાય ત્યાં સુધી તળો.'],
 ['Drain on a rack and serve warm with coconut chutney or tea.','जाली पर निकालकर नारियल चटनी या चाय के साथ गरम परोसें।','જાળી પર કાઢી નાળિયેરની ચટણી કે ચા સાથે ગરમ પીરસો.']
],['Flatten the discs thinly; thick patties remain soft rather than developing Maddur vada’s signature snap.','वड़े पतले दबाएँ; मोटे वड़े मद्दूर की खास कुरकुराहट के बजाय नरम रहेंगे।','વડા પાતળા દબાવો; જાડા વડા મદ્દુરની ખાસ કરકરી મજાને બદલે નરમ રહેશે.'],'https://hebbarskitchen.com/maddur-vada-recipe-maddur-vade/');

add('kuzhi-paniyaram','Kuzhi Paniyaram','कुज़ी पनियारम','કુઝી પનિયારમ','Tamil',780,[
 ['idli rice',300,'g','इडली चावल','ઇડલી ચોખા'],['split urad dal',90,'g','धुली उड़द दाल','છોલેલી અડદ દાળ'],['fenugreek seeds',4,'g','मेथी दाना','મેથીના દાણા'],['water for soaking and grinding',700,'ml','भिगोने और पीसने का पानी','પલાળવા અને પીસવા માટે પાણી'],['red onion, finely chopped',120,'g','बारीक कटा लाल प्याज','બારીક સમારેલી લાલ ડુંગળી'],['green chillies, chopped',12,'g','कटी हरी मिर्च','સમારેલાં લીલાં મરચાં'],['curry leaves, chopped',12,'g','कटे करी पत्ते','સમારેલાં મીઠા લીમડાનાં પાન'],['mustard seeds',6,'g','राई','રાઈ'],['salt',9,'g','नमक','મીઠું'],['oil for cooking',65,'ml','पकाने का तेल','રાંધવા માટે તેલ']
],[
 ['Rinse rice and urad separately. Soak rice in part of the water, and urad with fenugreek in another portion, until soft.','चावल और उड़द अलग धोएँ। चावल को कुछ पानी में और उड़द को मेथी के साथ अलग पानी में नरम होने तक भिगोएँ।','ચોખા અને અડદ અલગ ધુઓ. ચોખાને થોડા પાણીમાં અને અડદને મેથી સાથે બીજા પાણીમાં નરમ થાય ત્યાં સુધી પલાળો.'],
 ['Grind urad fluffy and rice slightly grainy with only enough measured water. Mix, cover and ferment in a warm place until airy and gently risen.','उड़द को फूला और चावल को हल्का दरदरा पीसें, दिए पानी का बस ज़रूरी भाग लें। मिलाकर ढकें और गरम जगह हवादार उठने तक खमीर करें।','અડદને ફૂલેલું અને ચોખાને થોડા દાણાદાર પીસો, આપેલું પાણી જરૂર મુજબ જ લો. ભેળવી ઢાંકો અને ગરમ જગ્યાએ હવાદાર ઊઠે ત્યાં સુધી આથો આવવા દો.'],
 ['Heat a little oil; crackle mustard seeds and cook onion, chilli and curry leaves until onion softens. Cool slightly and fold into the batter with salt.','थोड़े तेल में राई चटकाएँ और प्याज, मिर्च, करी पत्ते प्याज नरम होने तक पकाएँ। थोड़ा ठंडा कर नमक सहित घोल में मिलाएँ।','થોડા તેલમાં રાઈ તડકાવો અને ડુંગળી, મરચાં, મીઠા લીમડાનાં પાન ડુંગળી નરમ થાય ત્યાં સુધી રાંધો. થોડું ઠંડું કરી મીઠા સાથે ખીરામાં ભેળવો.'],
 ['Oil the hollows of a paniyaram pan and fill each mostly full. Cover and cook on medium-low heat until bottoms are golden.','पनियारम तवे के खानों में तेल लगाकर लगभग भरें। ढककर मध्यम-धीमी आँच पर नीचे सुनहरा होने तक पकाएँ।','પનિયારમ તવાના ખાડાંમાં તેલ લગાવી લગભગ ભરો. ઢાંકી મધ્યમ-ધીમા તાપે તળિયું સોનેરી થાય ત્યાં સુધી રાંધો.'],
 ['Turn each ball and cook the other side until crisp outside and fluffy inside. Serve hot with coconut chutney.','हर गोला पलटकर दूसरी ओर पकाएँ ताकि बाहर कुरकुरा और भीतर फूला नरम रहे। नारियल चटनी के साथ गरम परोसें।','દરેક ગોળી ફેરવી બીજી બાજુ રાંધો જેથી બહાર કરકરું અને અંદર ફૂલેલું નરમ રહે. નાળિયેરની ચટણી સાથે ગરમ પીરસો.']
],['The batter needs real fermentation for light centres; a heavy unfermented batter makes dense paniyaram.','भीतर हल्के बनाने के लिए घोल को सच में खमीर होना चाहिए; बिना खमीर का घोल भारी पनियारम बनाता है।','અંદર હલકું બનાવવા ખીરામાં ખરેખર આથો આવવો જોઈએ; વગર આથાનું ખીરું ભારે પનિયારમ બનાવે છે.'],'https://www.vegrecipesofindia.com/masala-paniyaram-recipe/');

add('konkani-phodi','Konkani Phodi','कोंकणी फोड़ी','કોંકણી ફોડી','Konkani',35,[
 ['raw green bananas',500,'g','कच्चे हरे केले','કાચાં લીલાં કેળાં'],['rice flour',85,'g','चावल का आटा','ચોખાનો લોટ'],['fine semolina',65,'g','बारीक सूजी','બારીક રવો'],['red chilli powder',7,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['turmeric powder',3,'g','हल्दी','હળદર'],['tamarind pulp',18,'g','इमली का गूदा','આંબલીનો માવો'],['salt',8,'g','नमक','મીઠું'],['water',45,'ml','पानी','પાણી'],['coconut oil',90,'ml','नारियल तेल','નાળિયેરનું તેલ']
],[
 ['Peel raw bananas and slice lengthwise into medium-thin ovals. Keep slices in water briefly, then drain and pat completely dry.','कच्चे केले छीलकर लंबाई में मध्यम पतले अंडाकार टुकड़े काटें। थोड़ी देर पानी में रखें, फिर छानकर पूरी तरह सुखाएँ।','કાચાં કેળાં છોલી લંબાઈમાં મધ્યમ પાતળા અંડાકાર કટકા કરો. થોડી વાર પાણીમાં રાખી પછી નિતારી સંપૂર્ણ સુકવો.'],
 ['Mix tamarind with water, chilli, turmeric and salt. Rub this thin spice coating over all banana slices; rest until absorbed.','इमली को पानी, मिर्च, हल्दी और नमक से मिलाएँ। यह पतला मसाला केले के टुकड़ों पर मलें; सोखने तक रखें।','આંબલીને પાણી, મરચું, હળદર અને મીઠા સાથે ભેળવો. આ પાતળો મસાલો કેળાના કટકાઓ પર ચોળો; શોષાય ત્યાં સુધી રાખો.'],
 ['Mix rice flour and semolina on a plate. Coat both sides of every slice and shake off loose flour.','थाली में चावल का आटा और सूजी मिलाएँ। हर टुकड़े के दोनों ओर लपेटें और ढीला आटा झाड़ें।','થાળીમાં ચોખાનો લોટ અને રવો ભેળવો. દરેક કટકાની બંને બાજુ ઢાંકો અને છૂટો લોટ ઝાડો.'],
 ['Heat a thin layer of coconut oil in a skillet. Lay slices in one layer and shallow-fry over medium heat until the undersides are reddish golden.','तवे में नारियल तेल की पतली परत गरम करें। टुकड़े एक परत में रखकर मध्यम आँच पर नीचे लाल-सुनहरा होने तक सेंकें।','તવામાં નાળિયેરના તેલનો પાતળો પડ ગરમ કરો. કટકા એક પડમાં રાખી મધ્યમ તાપે તળિયું લાલસોનેરી થાય ત્યાં સુધી શેકો.'],
 ['Turn and cook the other side until banana is tender and coating crisp. Drain and serve with dal-rice.','पलटकर दूसरी ओर केला नरम और परत कुरकुरी होने तक पकाएँ। तेल छानकर दाल-चावल के साथ परोसें।','ફેરવી બીજી બાજુ કેળું નરમ અને પડ કરકરું થાય ત્યાં સુધી રાંધો. તેલ નિતારી દાળ-ભાત સાથે પીરસો.']
],['Do not crowd the skillet; trapped steam softens the rice-flour and semolina crust.','तवे पर भीड़ न करें; फँसी भाप चावल-सूजी की परत नरम कर देती है।','તવામાં ભીડ ન કરો; ભરાયેલી વરાળ ચોખા-રવાના પડને નરમ કરે છે.'],'https://www.cookingwithshobana.com/2021/06/kele-phodi-raw-banana-shallow-fry.html');

add('chura-bhuja','Chura Bhuja','चूड़ा भूजा','ચૂડા ભૂજા','Bihari',25,[
 ['thick flattened rice',400,'g','मोटा चूड़ा','જાડા પૌંઆ'],['raw peanuts',140,'g','कच्ची मूँगफली','કાચી મગફળી'],['green chillies',12,'g','हरी मिर्च','લીલાં મરચાં'],['curry leaves',12,'g','करी पत्ते','મીઠા લીમડાનાં પાન'],['turmeric powder',3,'g','हल्दी','હળદર'],['red chilli powder',4,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['salt',8,'g','नमक','મીઠું'],['mustard oil',65,'ml','सरसों तेल','સરસવનું તેલ']
],[
 ['Pick through flattened rice to remove husks. If the flakes feel damp, spread them until dry; do not soak or rinse.','चूड़े में से भूसी निकालें। दाने नम हों तो फैलाकर सुखाएँ; भिगोएँ या धोएँ नहीं।','પૌંઆમાંથી ફોતરાં કાઢો. દાણા ભીના લાગે તો પાથરી સુકવો; પલાળો કે ધુઓ નહીં.'],
 ['Heat mustard oil in a wide pan and fry peanuts over medium-low heat until browned and crisp; lift out.','चौड़े पैन में सरसों तेल गरम करके मूँगफली मध्यम-धीमी आँच पर भूरी कुरकुरी भूनें; निकाल लें।','પહોળી કડાઈમાં સરસવનું તેલ ગરમ કરી મગફળી મધ્યમ-ધીમા તાપે ભૂરા કરકરા શેકો; કાઢી લો.'],
 ['In the same oil crisp the chopped chillies and curry leaves. Add turmeric and chilli powder briefly without burning them.','उसी तेल में कटी मिर्च और करी पत्ते कुरकुरे करें। हल्दी और मिर्च पाउडर डालकर बिना जलाए जल्दी मिलाएँ।','એ જ તેલમાં સમારેલાં મરચાં અને મીઠા લીમડાનાં પાન કરકરાં કરો. હળદર અને મરચું પાઉડર નાખી બળે નહીં તેમ ઝટપટ ભેળવો.'],
 ['Add dry chura in batches and toss continuously over low heat until every flake turns crisp and lightly golden.','सूखा चूड़ा थोड़ा-थोड़ा डालें और धीमी आँच पर लगातार चलाकर हर दाना कुरकुरा और हल्का सुनहरा करें।','સૂકા પૌંઆ થોડા થોડા નાખો અને ધીમા તાપે સતત હલાવી દરેક દાણો કરકરો અને હળવો સોનેરી કરો.'],
 ['Return peanuts, season with salt and toss well. Cool fully before storing, or serve warm with tea.','मूँगफली वापस डालें, नमक मिलाकर अच्छी तरह चलाएँ। रखने से पहले पूरा ठंडा करें या चाय के साथ गरम परोसें।','મગફળી પાછી નાખો, મીઠું ભેળવી સારી રીતે હલાવો. સાચવતાં પહેલાં સંપૂર્ણ ઠંડું કરો અથવા ચા સાથે ગરમ પીરસો.']
],['Use thick dry flattened rice; thin flakes break and damp flakes become chewy.','मोटा सूखा चूड़ा लें; पतले दाने टूटते और नम दाने चबाने जैसे रह जाते हैं।','જાડા સૂકા પૌંઆ લો; પાતળા દાણા તૂટી જાય અને ભીના દાણા ચવાણા જેવા રહે છે.'],'https://www.steamingpot.com/chura-bhuja-with-peas/');

add('bhadang','Bhadang','भडंग','ભડંગ','Maharashtrian',25,[
 ['puffed rice',350,'g','मुरमुरे','મમરા'],['raw peanuts',140,'g','कच्ची मूँगफली','કાચી મગફળી'],['garlic, thinly sliced',40,'g','पतला कटा लहसुन','પાતળું સમારેલું લસણ'],['curry leaves',18,'g','करी पत्ते','મીઠા લીમડાનાં પાન'],['red chilli powder',8,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['turmeric powder',3,'g','हल्दी','હળદર'],['sugar',8,'g','चीनी','ખાંડ'],['salt',9,'g','नमक','મીઠું'],['peanut oil',85,'ml','मूँगफली तेल','મગફળીનું તેલ']
],[
 ['Warm puffed rice in a dry wide pan over low heat until crisp. Transfer to a large bowl without crushing it.','मुरमुरे चौड़े सूखे पैन में धीमी आँच पर कुरकुरे करें। बिना तोड़े बड़े कटोरे में निकालें।','મમરા પહોળી સૂકી કડાઈમાં ધીમા તાપે કરકરા કરો. તોડ્યા વગર મોટી વાટકીમાં કાઢો.'],
 ['Heat peanut oil; roast peanuts until crisp and remove. In the same oil fry sliced garlic slowly until golden, then crisp curry leaves.','मूँगफली तेल गरम करके दाने कुरकुरे भूनकर निकालें। उसी तेल में लहसुन की फाँकें धीरे सुनहरी करें, फिर करी पत्ते कुरकुरे करें।','મગફળીનું તેલ ગરમ કરી દાણા કરકરા શેકી કાઢો. એ જ તેલમાં લસણની ફાંકો ધીમે સોનેરી કરો, પછી મીઠા લીમડાનાં પાન કરકરા કરો.'],
 ['Turn heat low and stir chilli powder, turmeric, sugar and salt into the fragrant oil for only a moment.','आँच धीमी करके महकते तेल में मिर्च पाउडर, हल्दी, चीनी और नमक बस पलभर मिलाएँ।','તાપ ધીમો કરી સુગંધિત તેલમાં મરચું પાઉડર, હળદર, ખાંડ અને મીઠું માત્ર ક્ષણભર ભેળવો.'],
 ['Pour spiced oil over puffed rice, add peanuts and toss with two spoons until all grains are evenly reddish and glossy.','मसालेदार तेल मुरमुरों पर डालें, मूँगफली मिलाएँ और दो चम्मच से चलाएँ ताकि सारे दाने बराबर लाल और चमकदार हों।','મસાલાવાળું તેલ મમરા પર રેડો, મગફળી ભેળવો અને બે ચમચીથી હલાવો જેથી બધા દાણા સરખા લાલ અને ચમકતા થાય.'],
 ['Cool completely to regain crunch and store airtight; serve as a dry Kolhapuri snack.','पूरा ठंडा करके फिर कुरकुरा होने दें और बंद डिब्बे में रखें; सूखे कोल्हापुरी नाश्ते की तरह परोसें।','સંપૂર્ણ ઠંડું કરીને ફરી કરકરું થવા દો અને હવાચુસ્ત ડબ્બામાં રાખો; સૂકા કોલ્હાપુરી નાસ્તા તરીકે પીરસો.']
],['Add chilli on low heat so it colours the rice without scorching and tasting bitter.','मिर्च धीमी आँच पर डालें ताकि मुरमुरों में रंग आए पर जलकर कड़वी न हो।','મરચું ધીમા તાપે નાખો જેથી મમરાને રંગ આવે પણ બળીને કડવું ન થાય.'],'https://madhurasrecipe.com/snacks/kolhapuri-bhadang-marathi-recipe');

add('chanachur','Chanachur','चानाचुर','ચાનાચુર','Bengali',45,[
 ['fine gram-flour sev',200,'g','बारीक बेसन सेव','બારીક ચણાના લોટની સેવ'],['fried split Bengal gram',120,'g','तली चना दाल','તળેલી ચણા દાળ'],['fried split moong dal',100,'g','तली मूँग दाल','તળેલી મગ દાળ'],['raw peanuts',130,'g','कच्ची मूँगफली','કાચી મગફળી'],['plain boondi',75,'g','सादी बूंदी','સાદી બૂંદી'],['curry leaves',12,'g','करी पत्ते','મીઠા લીમડાનાં પાન'],['dried red chillies',8,'g','सूखी लाल मिर्च','સૂકાં લાલ મરચાં'],['red chilli powder',5,'g','लाल मिर्च पाउडर','લાલ મરચું પાઉડર'],['roasted cumin powder',5,'g','भुना जीरा पाउडर','શેકેલું જીરું પાઉડર'],['black salt',5,'g','काला नमक','સંચળ'],['mustard oil',45,'ml','सरसों तेल','સરસવનું તેલ']
],[
 ['Break long sev into short strands. Check that the fried dal and boondi are fully dry and crisp before combining.','लंबी सेव छोटे टुकड़ों में तोड़ें। मिलाने से पहले तली दाल और बूंदी पूरी सूखी कुरकुरी हों।','લાંબી સેવ નાના ટુકડાં કરો. ભેળવતાં પહેલાં તળેલી દાળ અને બૂંદી સંપૂર્ણ સૂકી કરકરી હોય તે તપાસો.'],
 ['Heat mustard oil in a broad pan. Fry peanuts over medium-low heat until brown, then lift out; crisp curry leaves and whole dried chillies in the same oil.','चौड़े पैन में सरसों तेल गरम करें। मूँगफली मध्यम-धीमी आँच पर भूरी भूनकर निकालें; उसी तेल में करी पत्ते और साबुत सूखी मिर्च कुरकुरी करें।','પહોળી કડાઈમાં સરસવનું તેલ ગરમ કરો. મગફળી મધ્યમ-ધીમા તાપે ભૂરાં શેકી કાઢો; એ જ તેલમાં મીઠા લીમડાનાં પાન અને આખાં સૂકાં મરચાં કરકરાં કરો.'],
 ['Turn heat off. Add sev, both fried dals, boondi and peanuts, tossing gently so fragile strands do not crumble.','आँच बंद करें। सेव, दोनों तली दालें, बूंदी और मूँगफली डालकर हल्के मिलाएँ ताकि नाज़ुक सेव न टूटे।','તાપ બંધ કરો. સેવ, બંને તળેલી દાળ, બૂંદી અને મગફળી નાખી હળવે ભેળવો જેથી નાજુક સેવ ન તૂટે.'],
 ['Sprinkle chilli powder, roasted cumin and black salt; toss repeatedly for an even spicy-tangy coating.','मिर्च पाउडर, भुना जीरा और काला नमक छिड़कें; बराबर तीखा-खट्टा लेप चढ़ाने के लिए बार-बार हल्के मिलाएँ।','મરચું પાઉડર, શેકેલું જીરું અને સંચળ છાંટો; સરખો તીખોખાટો પડ ચડે માટે વારંવાર હળવે ભેળવો.'],
 ['Let the mixture cool fully, then store airtight or serve a small bowl with tea or puffed rice.','मिश्रण पूरी तरह ठंडा कर बंद डिब्बे में रखें या चाय व मुरमुरे के साथ छोटी कटोरी परोसें।','મિશ્રણ સંપૂર્ણ ઠંડું કરી હવાચુસ્ત ડબ્બામાં રાખો અથવા ચા અને મમરા સાથે નાની વાટકી પીરસો.']
],['Store-bought plain sev, dal and boondi are measured components here; use fresh unsalted ones so the final seasoning remains balanced.','यहाँ तैयार सादी सेव, दाल और बूंदी मापे हुए घटक हैं; ताज़े बिना नमक वाले लें ताकि अंतिम मसाला संतुलित रहे।','અહીં તૈયાર સાદી સેવ, દાળ અને બૂંદી માપેલા ઘટકો છે; તાજાં વગર મીઠાવાળાં લો જેથી છેલ્લો મસાલો સંતુલિત રહે.'],'https://eisamay.com/amp/story/lifestyle/know-more/recipe-how-to-make-bengali-chanachur-at-home/85832169.cms');

const intake=JSON.parse(await fs.readFile('catalog/intake/friend-dishes.json','utf8'));
for(const e of entries){
 const c=intake.candidates.find(x=>x.id===e.id);
 if(!c)throw new Error(`No source candidate: ${e.id}`);
 const draft={sourceReviewId:c.sourceReviewId,id:e.id,status:'draft-fourth-100-intake-batch',name:e.name,cuisine:e.cuisine,categories:['Snacks'],baseServings:4,prepAndCookMinutes:e.mins,
 ingredients:e.ingredients.map(x=>({name:x[0],qty:x[1],unit:x[2]})),steps:e.steps.map(x=>x[0]),tips:[e.tip[0]],
 translations:{hi:{name:e.hi,ingredients:e.ingredients.map(x=>x[3]),steps:e.steps.map(x=>x[1]),tips:[e.tip[1]]},gu:{name:e.gu,ingredients:e.ingredients.map(x=>x[4]),steps:e.steps.map(x=>x[2]),tips:[e.tip[2]]}},
 reference:{url:e.url,use:'Dish identity and method; quantities and wording independently authored for this catalogue.'},photoDraft:`catalog/intake/photos/${e.id}.png`,photoReview:'Visually reviewed for dish identity, appetizing realistic appearance and photo quality on 2026-10-06.'};
 await fs.writeFile(`catalog/intake/${e.id}-draft.json`,JSON.stringify(draft,null,2)+'\n');
}
console.log(`Prepared ${entries.length} recipes`);
